### ISSUE TITLE
Option to push other than gh-pages branch

### ISSUE THREAD

**Issue by rajmahendra** [ajoberstar/gradle-git#100]
if i use primary repo for my org as website orgname.github.io  github default uses `master` branch as `gh-pages`

So its good to provide options to push to any branch other than `gh-pages`

example
      branch = 'master'   // default is 'gh-pages'

**Comment by ajoberstar** [comment]
Already supported, see the [GithubPagesPluginExtensin](http://ajoberstar.org/gradle-git/docs/groovydoc/org/ajoberstar/gradle/git/ghpages/GithubPagesPluginExtension.html).

```
githubPages {
  targetBranch = 'master'
}
```

**Comment by rajmahendra** [comment]
Oops sorry I missed it.  Thank you.
