### ISSUE TITLE
Question: independent versioning of multiple release branches

### ISSUE THREAD

**Issue by martinda** [ajoberstar/gradle-git#101]
I would like to know if this plugin would be adequate in the following scenario. I am thinking of having a multiple long term support release branches, and I would like to use semantic versioning on each release branch independently. This idea comes from the diagram shown on this page (you have to scroll down for the diagram):
http://blogs.atlassian.com/2013/10/inside-atlassian-feature-branching-on-the-stash-team/

Do you think this plugin is a good choice for this scenario? Thanks.

**Comment by ajoberstar** [comment]
Yes, release branches are supported by `gradle-git`. Take a look at the options already provided in the [source](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy#L81). If those existing branch enforcement strategies don't meet your needs you can use `Strategies.fromBranchPattern` to use your own pattern. Basically this would mean that if the current branch matches the pattern, the project's version must match the indicated version in the branch name. If it doesn't it will blow up. If it can make a major or minor version increment to make it match up, it will do that.

Let me know if you still have questions.
