### ISSUE TITLE
Changing Existing Version Strategy Scope values

### ISSUE THREAD

**Issue by eyedol** [ajoberstar/gradle-git#104]
Is there a quick way to change the `scopes` values for an existing version strategy?. Say with the `PRE_RELEASE` strategy if I want to change the `scopes` from `['milestone', 'rc']` to say `['alpha','beta','rc'] how do I go about it. Extending `Strategies` isn't possible since it's a final class. Writing a version strategy just to change scope names is too much work I feel.

Let me know where to ask these kind of questions instead of opening up an issue. Thanks.

**Comment by eyedol** [comment]
Following up on this. Will a `PR` like this be something you will be interested in merging? Want to know before attempting to send in the PR.

```java
final class Strategies {
...
    /**
	 * Provides "alpha", "beta" and "rc" stages that can only be used in clean repos
	 * and will enforce precedence. The pre-release-alpha-beta component will always be set
	 * to the stage with an incremented count to disambiguate successive
	 * releases of the same stage. No build metadata component will be added.
	 */
	static final SemVerStrategy PRE_RELEASE_ALPHA_BETA = DEFAULT.copyWith(
		name: 'pre-release-alpha-beta',
		stages: ['alpha', 'beta', 'rc'] as SortedSet,
		preReleaseStrategy: all(PreRelease.STAGE_FIXED, PreRelease.COUNT_INCREMENTED)
	)
...
}
```

**Comment by ajoberstar** [comment]
My original intent was to provide basic building blocks and examples with the `opinion` package. In that vein, I would suggest something like this:

```groovy
apply plugin: 'org.ajoberstar.release-opinion'

release {
  version Strategy.PRE_RELEASE.copyWith(stages: ['alpha', 'beta', 'rc'] as SortedSet)
}
```

However, I also think alpha, beta, rc is a pretty common approach, so it may make sense to provide out of box. So yeah, I'd merge that. Thanks for the proposal!
