### ISSUE TITLE
Infer repoUri from current repo

### ISSUE THREAD

**Issue by pvdissel** [ajoberstar/gradle-git#108]
Currently you need to provide an repoUri, which is cloned, changed, committed, and pushed back to the remote.

Would it be possible to do all this, locally, based on the local repository the gradle build is executed in. Maybe separating the generating from the publishing of the gh-pages branch.

How would I (want) to see this work?
- Make `repoUri` optional, which by-default uses the local repository directory
- Add a new task named something like `generateGhPages` or `buildGhPages`, which only:
  - Clone the repository from local to `workingPath` (like it currently does with the clone from repoUri, but then from local)
  - Creates the wanted `targetBranch`
  - Executes the `pages` `CopySpec` to generate/build the `targetBranch` content
- Change the current `publishGhPages` task to:
  - Depend on the `generateGhPages` task
  - To only publish to the remote repo
  - To infer the remote repo from the local repository' `origin` remote config
- Maybe an `inferRepoUri` or `useLocalRepo` option would be useful and/or less magical for users.

This would make the plugin:
- even easier to use (less to configure == easier :smile:)
- not bind the gradle configuration to the github repository, which possibly interfere' with forking. As forker it would be nice to be able to test the *ghPages tasks without needing push access on the upstream remote repository

Or is there a technical reason that the repoUri is currently not optional and/or inferred?

**Comment by ajoberstar** [comment]
I haven't tried either of these, but I think there are a couple complications:

- Cloning from local is fine for testing, but it would cause problems if it was part of the general process. If your local `gh-pages` branch is up to date with the remote, your push would fail.
- Inferring the remote either needs to make assumptions about where the local repository is in your project or ask for that location.

I like the general idea, particularly breaking this into two tasks. Even if you didn't do the local piece, you could just run `generateGhPages` (maybe `prepareGhPages`?) and inspect that repository's status. If that would be common enough of a use case, there could be a task to print out the status of that repo after the `generateGhPages`. I definitely think the plugin should infer the remote, but that might fit better into a broader redesign of the gh-pages plugin.

What do you think?

**Comment by pvdissel** [comment]
Sounds good, keep changes small. This would make the following steps:
- Split `publishGhPages` into two tasks, `prepareGhPages` and `publishGhPages`
- Implement cloning from local, for testing purposes. `dryRun`?
- Try to implement remote infer from `origin` without broader redesign of the `gh-pages` plugin. As `origin` is probably the most common use-case. And let see how that works

I will try to get this implemented

**Comment by ajoberstar** [comment]
For each of those steps:

- Yep.
- Do you need a standard "clone from local" option if you could just run `generateGhPages` and see what you changed in the branch? This could run against the remote and wouldn't be able to break anything since the push didn't happen yet. Maybe a `dryRunGhPages` that runs `generateGhPages` and then prints out the status of the repo if more info is needed?
- It might be worth coming up with some interface ideas for this one before spending too much time on it. Inference has the danger of making too many assumptions and/or not being flexible enough.

Thanks for contributing!

**Comment by pvdissel** [comment]
@ajoberstar in 2a8f579 I've started implementing this. I've started with the splitting of the `prepareGhPages` and `publishGhPages`. This is all good and well, it works, but somehow I don't see the `prepareGhPages` task in the tasks list...
Do you have an idea why the `prepareGhPages` task is not shown in the tasks list of a project using this version of the plugin? Running `gradlew -m publishGhPages` does show the `prepareGhPages` task as to-be-executed before the `publishGhPages` task.
Any clue is appreciated :smile:

**Comment by ajoberstar** [comment]
Have you tried `gradlew tasks --all`? I think Gradle hides some tasks by default.

**Comment by pvdissel** [comment]
A correct, thanks. Came across the following, where Peter explains the logic:
 http://forums.gradle.org/gradle/topics/getting_custom_plugin_tasks_to_be_listed_when_gradle_tasks_is_called#reply_8122281
> The logic is the same for all tasks, whether they are declared in a build script or added by a plugin. A task will show up in gradle tasks if no other task depends on it or the task has a value set for its group property. gradle tasks --all will show all tasks.

Cool, then step 1 is fully implemented now :smile: 
- Split `publishGhPages` into two tasks, `prepareGhPages` and `publishGhPages`

@ajoberstar How do you want to do this? A PR for each step? Or all at once?

**Comment by ajoberstar** [comment]
Let's go with separate PRs.

**Comment by pvdissel** [comment]
ok, then this is the PR for step 1 :smile: 
@ajoberstar Can you review?

**Comment by ajoberstar** [comment]
Hmm.. not seeing any active PRs. Let me know when its up and I can take a look.

**Comment by pvdissel** [comment]
@ajoberstar sorry, must have been sleepy. The PR is now created as #109

**Comment by ajoberstar** [comment]
Hey @pvdissel, since there hasn't been any activity on this, I'm going to close it for now. Feel free to reopen if you want to pursue any other aspects of this issue.

**Comment by pvdissel** [comment]
Hmm, sorry. I've totally forgotten about this one. Will reopen it again when I come to it
