### ISSUE TITLE
how to set version to SNAPSHOT unless release task is present

### ISSUE THREAD

**Issue by dlethin** [ajoberstar/gradle-git#110]
I've just found this plugin today and it seems to be just what I'm looking for with enough flexibility to support a few scenarios we have for different projects with different branching/versioning strategies.

I spent a good amount of time reading the wiki, groovydoc, and code trying to research this first scenario:

I'm looking to have the default strategy to provide -SNAPSHOT releases, *unless** the release task is in the task graph.  In that case, I don't want any -SNAPSHOT in the version.  Just the Semantic M.m.p

Here's what I came up with in a test project that *seems* to work:

```gradle
import org.ajoberstar.grgit.Grgit
import org.ajoberstar.gradle.git.release.opinion.Strategies

buildscript {
  dependencies {
    classpath 'org.ajoberstar:gradle-git:1.1.0'
  }
}

//apply plugin: 'org.ajoberstar.release-opinion'
apply plugin: 'org.ajoberstar.release-base'

release {
	grgit = Grgit.open(project.file('.'))

	defaultVersionStrategy = Strategies.SNAPSHOT

}

task printVersion << {
	println version
}

gradle.taskGraph.whenReady {taskGraph ->
    if (taskGraph.hasTask(tasks.release)) {
		release.defaultVersionStrategy = Strategies.FINAL.copyWith(
			allowDirtyRepo: false)
    }
}
```

Is this the right way to approach this problem?  Perhaps I'm making this more complicated than it needs to be. But it seems to work, though I did experience a problem.

Near as I can tell, Strategies.FINAL has allowDirtyRepo set to false, and when I even force it to be false, it still seems to succeed even if I have uncommitted local changes.  Am I missing something here?

Lastly, perhaps a random and stupid question -- where does the "closure" method in this class -- for example, on line 45 here:

https://github.com/ajoberstar/gradle-git/blob/23eb7386d3f53b381a1a1f6a91fcef2e747deec5/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy

You're defining a static constant of a particular type, yet assigning a value which is a closure, not an object of type PartialSemVerStrategy as I would expect. Is this some kind of groovyism? 

When I was looking at the code trying to reverse engineer how to customize strategies,  I came across that and couldn't figure out how it worked.

Anyway, thanks for your work on this plugin.    It's very impressive.

**Comment by dlethin** [comment]
I figured out the error of my ways...  It looks like the default behavior of the opinion plugin is exactly what I needed.  I was just misunderstanding how things work.  I was concerned that having -Prelease.stage=final was going to put 'final' in my version string which I didn't want.

Then I was not realizing that that allowDirtyRepo doesn't apply to the default strategy you set.

I was also not seeing certain log messages unless I added -i which helped track down my confusion.

Still curious about my other question above, however as to what the "closure" method does.

Thanks again.

Cheers.

**Comment by ajoberstar** [comment]
Glad to hear you figured out your use case. I'll close this issue out.

I actually had trouble finding the `closure` method once you mentioned it. Turns out it's a static star import from [StrategyUtil](https://github.com/ajoberstar/gradle-git/blob/23eb7386d3f53b381a1a1f6a91fcef2e747deec5/src/main/groovy/org/ajoberstar/gradle/git/release/semver/StrategyUtil.groovy#L30). I usually avoid star imports, and this is more reason why they're a bad idea. The `closure` method's purpose is to easily make a PartialSemVerStrategy from a closure.
