### ISSUE TITLE
Provide a convenient way for publishGhPages to dependOn javadoc

### ISSUE THREAD

**Issue by shevek** [ajoberstar/gradle-git#113]
https://github.com/ajoberstar/gradle-git/wiki/org.ajoberstar.github-pages tells me how to consume the output of various tasks. It would really rock if somehow it were possible to ensure that the entire github-pages taskset ran AFTER those tasks (e.g. javadoc) were complete.

The simple case: publishGhPages.dependsOn(javadoc) works for now but if prepareGhPages is what does the copy, then when gradle-git next gets released, that will break. What I really want is a way to embed the task dependency in the source CopySpec using something like builtBy.

Can you please provide a simple example, recipe or mechanism?

Thank you.

S.

**Comment by shevek** [comment]
Please see also http://discuss.gradle.org/t/aggregating-taskoutput-filecollection-s-into-a-copyspec-with-builtby/9189

**Comment by ajoberstar** [comment]
Sterling's suggestion should do it. I updated the wiki page to reflect that.

**Comment by shevek** [comment]
It doesn't work because of the way the plugin is currently set up.

Sterling posts a further suggestion for an improvement to github-pages which would make it work in future. Do you mind converting this issue into a bug, which is effectively a request to make that change?

**Comment by ajoberstar** [comment]
Will do.

**Comment by shevek** [comment]
I'd love a 1.2.0-final on Central so I can capitalize on this improvement.

**Comment by ajoberstar** [comment]
Thanks for the reminder. Just pushed it out.

**Comment by shevek** [comment]
Thank you.

This works now: https://github.com/shevek/gradle-stdproject-plugin/commit/31d96f5ffe5e34ee4b86ea566964a36c21027a16
