### ISSUE TITLE
ReleasePlugin: Need prePush hook closure or something similar

### ISSUE THREAD

**Issue by fuschl** [ajoberstar/gradle-git#119]
I have implemented a custom VersionStrategy, but have to do some work *during* the release task, but *before* the push (of the new tag) happens.

Any idea? Maybe something like 

```groovy
release {
   ...
   prePush = { // my work}
}
```
Thanks,
fuschl

**Comment by ajoberstar** [comment]
Can you use a standard `doFirst` action?

``groovy
release {
  doFirst {  // your work }
}
```

**Comment by fuschl** [comment]
The doFirst closure is not available within the release plugin config closure block.
But it worked when adding my code at the end of  my infer(Project, Grgit) implementation:
```groovy
        project.getTasksByName('release', false).first().doFirst {
            nextVersion.store(project, versionPropertyFileName)

            [gitAddCommand(grgit), gitCommitCommand(grgit, nextVersion)].each {
                it.call()
            }
        }
```
The lookup of the release looks a bit like a hack, but's OK for me.

FYI: Our custom VersionStrategy infers a 4-digit version (major.minor.fix.build) which is Git-persisted in a simple version.properties file.
Thanks for your hint!

**Comment by ajoberstar** [comment]
Good point about the `release` extension shadowing. I forgot about that.

It's not much better but you could substitute:

```groovy
project.getTasksByName('release', false).first().doFirst {
```

with:

```groovy
project.tasks.release.doFirst {
```
