### ISSUE TITLE
Strategies *_BRANCH_MAJOR_MINOR_X do not work with nebula-release plugin

### ISSUE THREAD

**Issue by tschulte** [ajoberstar/gradle-git#121]
Nebula-release (https://github.com/nebula-plugins/nebula-release-plugin/) does use the BaseReleasePlugin and configures it to have some defaults. One of these is to automatically increment the minor instead of the patch. But this does not work when having a branch that should trigger the *_BRANCH_MAJOR_MINOR_X strategy.

E.g.: Last version is 1.2.5, create a branch release/1.3.x. The first version will be 1.3.0 as expected, but the second version on this branch will be 1.4.0 instead of 1.3.1.

**Comment by ajoberstar** [comment]
Thanks for submitting these two issues and the PR. I'll have a look through them and see if I have any further feedback or questions.

**Comment by ajoberstar** [comment]
Without having thought too deeply, I think I agree that MAJOR_MINOR_X should increment patch instead of passing through the the next strategy. It should really only pass through if the branch pattern doesn't match.

**Comment by ajoberstar** [comment]
Thanks again! This will be in 1.3.0.
