### ISSUE TITLE
Strategies *_BRANCH_MAJOR_X should always increment minor

### ISSUE THREAD

**Issue by tschulte** [ajoberstar/gradle-git#123]
This is related to #121. 

This time, when using nebula-release and a branch release/2.x, the first version is 2.0.0, the second version build on that branch 2.1.0. 

But when doing the same with vanilla gradle-git, the result will be 2.0.0 for the first release, and 2.0.1 for the second release.

I think when the branch matches the *_BRANCH_MAJOR_X strategy, the plugin should always increment the minor. With #121 applied, to get the current behaviour, one would have to name the branch to match MAJOR_MINOR_X.

With this change, one could have major-branches using the MAJOR_X pattern (e.g. release/2.x, release/3.x) to implement new features, but if for some reason someone needs a bugfix based on an earlier version, a new branch release/2.3.x can be created based on the tag v2.3.0 to cherry-pick some bugfix and create a version 2.3.1.

As I said, once #121 is applied, this is already possible with nebula-release, but might not be possible with vanilla gradle-git without changing the default fallback to useScope(MINOR) like nebula-release does.

I think this, in conjunction with #121, would better reflect the expected behaviour when using release branches with these patterns.

**Comment by tschulte** [comment]
I am currently implementing a semantic-release plugin based on the ideas from https://github.com/semantic-release/semantic-release. It will be based on gradle-git and I plan on using *_BRANCH_MAJOR_X and *_BRANCH_MAJOR_MINOR_X in addition to my own strategy.

Using MAJOR_MINOR_X is a no-brainer: When the strategy incremented the patch level, but the commits indicate a minor or even major level upgrade, the release should fail.

But using MAJOR_X in combination with my strategy would only work if the current behaviour of the MAJOR_X strategy is left unchanged. 

Maybe it is best to keep the MAJOR_X stragegy as it is now, and introduce two new MAJOR_X_0 strategies: 

```groovy
static final PartialSemVerStrategy ENFORCE_GITFLOW_BRANCH_MAJOR_X_0 = one(fromBranchPattern(~/^release(?:\/|-)(\d+)\.x\.0$/), useScope(ChangeScope.MINOR))

static final PartialSemVerStrategy ENFORCE_BRANCH_MAJOR_X_0 = one(fromBranchPattern(~/^(\d+)\.x\.0$/), useScope(ChangeScope.MINOR))
```

That way one could use following branch pattern:

- release/1.2.x to build what it says, 1.2.0, 1.2.1, 1.2.2, 1.2.3, ... (#121)
- release/1.x.0 to build what it says, 1.0.0, 1.1.0, 1.2.0, 1.3.0, ...
- release/1.x in combination with other strategies (using StrategyUtil.one()) to let the other strategies decide

If you think this is OK, I can prepare a pull request.

**Comment by ajoberstar** [comment]
Unless someone defaults to MAJOR (which is unlikely), I think the current behavior is appropriate. For your new MAJOR_X_0 strategies, I would lean towards you including those in your new plugin. If someone uses MINOR as their default scope, they would get the same result from the existing strategy.

Side point, possibly relevent to your plugin, I'm also working on a more general replacement for the version inference in [semver-vcs](https://github.com/ajoberstar/semver-vcs). Not sure how far off it is from being usable, but I am specifically aiming to better address the implications branches have on versioning.
