### ISSUE TITLE
files with ACLs or extended security information are considered different by grgit but the same by git

### ISSUE THREAD

**Issue by jzwolak** [ajoberstar/gradle-git#124]
I have a project where I copied a jar dependency from Windows to Mac OS X and included it in my repository.  The jar overwrites a previous version of itself in the repo.  Mac OS X takes some windows permissions with this file as "extended security information" (per the "ls" command's manual).  The extended security information appears to me to be an access control list.  When running "ls -l" a plus sign is displayed next to the permissions of the jar where there was none before.  Adding the "-e" flag shows the additional security information:

    application$ ls -l lib/thirdparty/simulator-windows-x86_64.jar 
    -rw-r--r--+ 1 jzwolak  staff  3082302 Jun 21 14:02 lib/thirdparty/simulator-windows-x86_64.jar
    application$ ls -e -l lib/thirdparty/simulator-windows-x86_64.jar 
    -rw-r--r--+ 1 jzwolak  staff  3082302 Jun 21 14:02 lib/thirdparty/simulator-windows-x86_64.jar
      0: user:jzwolak inherited allow read,write,execute,delete,append,readattr,writeattr,readextattr,writeextattr,readsecurity,writesecurity,chown

Now... running "git status" says everything is clean... but printing "grgit.status().clean" shows false and "grgit.status()" shows this:

    grgit status: org.ajoberstar.grgit.Status(staged:org.ajoberstar.grgit.Status$Changes(added:[], modified:[], removed:[]), unstaged:org.ajoberstar.grgit.Status$Changes(added:[], modified:[numerical_toolkit/test/madonna/test048_nested_if.exp, application/build.gradle, application/lib/thirdparty/simulator-windows-x86_64.jar], removed:[]))

Notice the file "application/lib/thirdparty/simulator-windows-x86_64.jar" is shown as modified even though "git status" shows it as clean:

    application$ git status lib/thirdparty/simulator-windows-x86_64.jar 
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean

This presents a problem as I cannot commit the change because the command line git doesn't see a change... yet I cannot release using Strategies.FINAL because this requires the working copy be clean and grgit doesn't think the working copy is clean.

I have a work around to this... delete the "modified" files and check them out freshly.  But it took me a couple hours to figure out what the problem was and I'm sure you'd like to know this difference between grgit and git.

I was using git 2.3.5 but upgraded to 2.4.6 and the same behavior is present.

I'm using gradle-git 1.2.0

**Comment by jzwolak** [comment]
Okay, so I see this is a problem with jgit and not gradle-git or grgit.  But the problem is pronounced for me when using gradle-git... so I'm not sure what we can/should do about it or if I should just file the bug with jgit.

**Comment by ajoberstar** [comment]
Yes, please submit the bug with JGit. If/when they fix it, let me know and I can upgrade to that version. Also, that upgrade would happen in grgit, so I've created a corresponding issue there and will close this one.
