### ISSUE TITLE
Plugin with id ... not found

### ISSUE THREAD

**Issue by c-mu** [ajoberstar/gradle-git#125]
I'd like to use your opinionated release plugin in a project, but it fails to load. I found Issue #32 explaining the reason being the use of imported buildscripts and a workaround to resolve the issue. However, with the release-opinion plugin the workaround fails also because the plugin tries to load the base plugin based on the id.

**Comment by ajoberstar** [comment]
I realize this isn't terribly helpful, but right now I don't plan on switching back to using the class names within the code to apply other plugins. Hopefully, Gradle will eventually improve support for those external buildscripts.

**Comment by c-mu** [comment]
Would you consider implementing it as a fallback? Use the apply-by-plugin id as default, only if it fails resort back to apply based on classname. That way you'd compensate a shortcoming of gradle, while limiting efforts when gradle finally comes round to fix their bug. 
As it is the release-opinion plugin can't be used in gradle projects using imported buildscripts. It seems you have put a lot of thought into the versioning strategies, and it would be shame if those were wasted due to such triviality.

**Comment by ajoberstar** [comment]
I definitely understand that viewpoint. My rationale might seem unreasonable, but here it is:

- This has been a longstanding limitation of Gradle that I've never seen a formal Jira ticket for, so I don't get the impression they have any plans to fix it.
- Their newer features, such as the `plugins` block and `pluginManager` prioritize IDs over classes. It seems like that's the direction their leaning going forward.
- Using IDs also allows more flexibility in cutting build-time dependencies between plugin JARs. I've been gradually breaking pieces of my plugins off into separate more general plugins, so this is a plus on my side.

The workaround in this particular case would be to use the `org.ajoberstar.release-base` plugin, but configure it similar to `org.ajoberstar.release-opinion`. There's not too much there to duplicate. The tag message piece is the only substantial piece of code, but you could probably do something simpler if you didn't want all of that code.

```
apply plugin: org.ajoberstar.gradle.git.release.base.BaseReleasePlugin

release {
  versionStrategy RebuildVersionStrategy.INSTANCE
  versionStrategy Strategies.DEVELOPMENT
  versionStrategy Strategies.PRE_RELEASE
  versionStrategy Strategies.FINAL
  defaultVersionStrategy = Strategies.DEVELOPMENT
}
```
