### ISSUE TITLE
Wrong commit being tagged

### ISSUE THREAD

**Issue by disconsented** [ajoberstar/gradle-git#126]
Essentially one commit in the master branch is constantly being used for tags and I am not sure why.
[This](https://github.com/disconsented/ANSSRPG/releases/tag/1.7.10-v0.1.15f1ce1) is an example tag(should be "15f1ce1" when it is "af76a2b ")

[build.gradle](https://github.com/disconsented/ANSSRPG/blob/c20096ecc6c9cb1e96dbcef68e3ebbd5489003d4/build.gradle#L106-L114) [travis.yml](https://github.com/disconsented/ANSSRPG/blob/c20096ecc6c9cb1e96dbcef68e3ebbd5489003d4/.travis.yml)

Any ideas on how to resolve this?
(On a side note is it possible to set a github release to pre-release?)

**Comment by ajoberstar** [comment]
I notice you have a println in there that prints out what it *should* be tagging. Does that match up with the hash that shows up in the version number (151ce1) or the one that actually gets tagged (af76a2b)?

As for your side point, `gradle-git` doesn't do anything with Github right now, besides the gh-pages support.

**Comment by disconsented** [comment]
[The println reports that it is trying to tag 15f1ce1](https://travis-ci.org/disconsented/ANSSRPG/builds/75890360#L418)

**Comment by ajoberstar** [comment]
Just cloned your repo and ran the task. It correctly put the tag on the 15f1ce1 commit. Is your Travis build configured to push the tags up to Github? If so, I'm not sure what's going on in that environment that would make it tag the wrong commit.

Unrelated to your issue, your `tagRelease` task currently runs at configuration time in Gradle, which means it runs regardless of whether you want it to or not. You need to make sure it's one of the actions (via doFirst or doLast) to make this happen:

```groovy
task tagRelease {
  doLast {
    println 'Attempting to apply tag ' + version + ' to commit ' + gitHash
    repo.tag.add {
        name = version
        message = "Release of ${version}"
        force = true
        pointsTo = gitHash
    }
  }
}
```

**Comment by disconsented** [comment]
Ran gradle tagRelease locally and it says it succeeded however the tag does not appear on the repo, did I miss something silly? (and github's IRC service doesn't respond that it was tagged)

**Comment by disconsented** [comment]
I believe this is now an authentication issue adding in repo.push allowed me to push the tag correctly however how do I go about doing this for a CI environment(or how do you authenticate via command line)?

**Comment by ajoberstar** [comment]
Authentication in grgit is controlled using the options noted in [AuthConfig](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/auth/AuthConfig.html). As for how to do this in Travis, I can't really say, as I haven't tried it before.
