### ISSUE TITLE
cannot use in "apply from" file

### ISSUE THREAD

**Issue by paleozogt** [ajoberstar/gradle-git#128]
If I try to use gradle-git from an "apply from" file (e.g., ```apply from: 'foobar.gradle'```) it fails with
```
Cannot cast object 'org.ajoberstar.grgit.Grgit@6b0f266e' with class 'org.ajoberstar.grgit.Grgit' to class 'org.ajoberstar.grgit.Grgit'
```

However, the same code will work fine if its directly in a build.gradle file.

Here's the code:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.ajoberstar:gradle-git:1.2.0'
    }
}

import org.ajoberstar.grgit.Grgit
import org.ajoberstar.gradle.git.release.opinion.Strategies

ext.git = Grgit.open(rootProject.projectDir)
ext.versionCode = git.log().size()
apply plugin: 'org.ajoberstar.release-opinion'
release {
    grgit = git
}

logger.lifecycle("version {}, versionCode {}", project.version, project.versionCode)
```

**Comment by ajoberstar** [comment]
Seems like it's loading Grgit in multiple classloaders. I would suspect this is a general Gradle limitation.

**Comment by ajoberstar** [comment]
That's just a guess though. May be worth doing some searches on the Grade forum.

**Comment by paleozogt** [comment]
From what I can gather, an "apply from" runs in its own classloader, which is why it needs it own buildscript block.  But since gradle-git is loaded in the "apply from" classloader, I'm not sure what's going wrong.

**Comment by ajoberstar** [comment]
Interesting...

**Comment by paleozogt** [comment]
Ah, I think I'm starting to understand this a bit better.

I missed a part of my example code.  It needs to look like this:

```
// build.gradle

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.ajoberstar:gradle-git:1.2.0'      // necessary or the later 'apply plugin' won't work
    }
}

apply from: 'version-utils.gradle'
```

```
// version-utils.gradle

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.ajoberstar:gradle-git:1.2.0'
    }
}

import org.ajoberstar.grgit.Grgit
import org.ajoberstar.gradle.git.release.opinion.Strategies
try {
    ext.git = Grgit.open(projectDir)
    ext.versionCode = git.log().size()
    apply plugin: 'org.ajoberstar.release-opinion'
    release {
        grgit = git              // cannot cast
    }
} catch (e) {
    ext.git= null
    ext.versionCode= 0
    throw e
}
logger.lifecycle("version {}, versionCode {}", project.version, project.versionCode)
```

So the 'apply plugin' is happening in the main gradle classloader, while the ```Grgit.open``` is happening in the 'apply from' classloader.  I'm not well-versed with classloaders, but it seems you can't copy references across classloaders?

**Comment by paleozogt** [comment]
What I'm trying to do with this 'apply from' thing is move the gradle-git boiler-plate out of the main gradle script and into something that can just be included.

I wonder... is there a way to have gradle-git instantiate its own grgit instance when 'apply plugin' is called?  I just want to use the defaults, so it seems sort of unnecessary to need to explicitly create the grgit.

**Comment by ajoberstar** [comment]
Correct if the same class is loaded in two different classloaders, the instances from the two classloaders aren't compatible. Does it work to remove the `buildscript` block from `version-utils.gradle`?

I added a `org.ajoberstar.grgit` plugin in 1.2.0 that just sets a `grgit` property on the project with the project's repository opened. I haven't integrated that with the other plugins yet, but if you wire it yourself maybe it will do what you were looking for:

```groovy
apply plugin: 'org.ajoberstar.grgit'

release {
  grgit = project.grgit
}
```

**Comment by paleozogt** [comment]
That works pretty well!

**Comment by ajoberstar** [comment]
Great! I'll add an issue to track getting the other plugins integrated with `org.ajoberstar.grgit`.
