### ISSUE TITLE
Diagnosing Problem pushing to remote

### ISSUE THREAD

**Issue by disconsented** [ajoberstar/gradle-git#129]
[Logs](https://travis-ci.org/disconsented/ANSSRPG#L193-L297)
[build.gradle](https://github.com/disconsented/ANSSRPG/blob/build/build.gradle)
[gradle.properties](https://github.com/disconsented/ANSSRPG/blob/build/gradle.properties)
[travis.yml](https://github.com/disconsented/ANSSRPG/blob/build/.travis.yml)

How do I go about finding why the tags failed to push?
Tried this locally and managed to get it to push successfully

**Comment by ajoberstar** [comment]
You could try running in debug mode (--debug). Not sure if that will provide anything more about the failure but might say more about what it was doing before.

It almost seems like a permissions issue. Are you passing the same credentials in locally and in Travis?

**Comment by disconsented** [comment]
I do believe that the credentials are right however according to this (https://travis-ci.org/disconsented/ANSSRPG#L288-L289) I am pushing to the wrong place. How do I change it from attempting to push from "git://github.com/disconsented/ANSSRPG.git" to "https://github.com/disconsented/ANSSRPG.git" ?

**Comment by ajoberstar** [comment]
Maybe there's a way to make Travis clone it with a different URI? Otherwise you'd have to modify the remote before doing the push. Right now, Grgit just supports adding and listing remotes, so it would have to be via CLI or JGit.

**Comment by disconsented** [comment]
With the help of the travis guys I got it sorted [issue](https://github.com/travis-ci/travis-ci/issues/4705),[soultion](https://github.com/disconsented/ANSSRPG/blob/9b7fd8eb9cbd312858116bbd6bc84a511236c294/.travis.yml#L16)
