### ISSUE TITLE
Is it possible to clone/checkout a specific branch/tag/commit?

### ISSUE THREAD

**Issue by marceloverdijk** [ajoberstar/gradle-git#13]
With the GitClone task it's possible to clone the repo.
Is it also possible to checkout a certain tag / commit?

**Comment by hariom12** [comment]
Hi,

Can you please update, any progress on this?

Thanks,
DKS

**Comment by ajoberstar** [comment]
I would suggest trying [grgit](https://github.com/ajoberstar/grgit) to see if it meets your use case. If it does not, please open an issue there. This one's very stale (referencing a long outdated version of gradle-git).
