### ISSUE TITLE
publishGhPages failing silently

### ISSUE THREAD

**Issue by chris-martin** [ajoberstar/gradle-git#132]
```
> ./gradlew publishGhPages
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:javadoc UP-TO-DATE
:prepareGhPages UP-TO-DATE
:publishGhPages SKIPPED

BUILD SUCCESSFUL

Total time: 1.464 secs
```

Nothing is pushed to git, no error output either. I'm new to Gradle, is there something I'm missing?

**Comment by chris-martin** [comment]
Sorry, seems like something did get pushed. Not sure why I didn't see it. Some more output on the command line would be very nice... But I guess this issue is invalid.

**Comment by ajoberstar** [comment]
I think this feature is the one that could help with the lack of output: ajoberstar/grgit#75. Not sure when I'll get to it, but I agree that it's a good idea.
