### ISSUE TITLE
Add option to generate "git.properties" file

### ISSUE THREAD

**Issue by balteo** [ajoberstar/gradle-git#133]
I am in reference to the [official Spring Boot documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-git-commit-information) which mentions the **gradle-git** plugin.

It would be nice to have a way to generate a git.properties file containing various information such as *git.branch* or *git.commit* and place it into the jar as required by Spring Boot (see above link).

Is this possible already? If so is it documented?

I would be grateful for some feedback.

**Comment by ajoberstar** [comment]
There's no pre-configured support for making a `git.properties` file equivalent with that Maven plugin. However, all of that information should be available from `grgit`. This certainly could be added and would be a welcome contribution, if someone has time before I can get to it.

**Comment by ajoberstar** [comment]
The Grgit [docs](http://ajoberstar.org/grgit/docs/groovydoc/index.html?org/ajoberstar/grgit/Grgit.html) can point you to the available operations.

**Comment by ajoberstar** [comment]
This probably would make more sense on its own, so I'm going to close this.
