### ISSUE TITLE
diff

### ISSUE THREAD

**Issue by omgnick** [ajoberstar/gradle-git#135]
I use grgit.show and want to see full path to changed files, but instead I receive only top level folders names that contains changed files. Is there any way to get a list of changed files (relative or full path to files)?

**Comment by ajoberstar** [comment]
Forgot to test show on subdirectories, turns out it's a bug (tracking in grgit#78). I'm pushing a fix up now but won't be releasing right away.

**Comment by ajoberstar** [comment]
This is getting releases in 1.3.1 (in a few minutes)

**Comment by ajoberstar** [comment]
Technically fixed in grgit 1.4.1, but bumping gradle-git's dependency on grgit as part of the gradle-git 1.3.1
