### ISSUE TITLE
Release task should work in "detached HEAD" state

### ISSUE THREAD

**Issue by tschulte** [ajoberstar/gradle-git#137]
Some CI servers do checkout `branch^{commit}` instead of the branch HEAD. I have seen this with Jenkins and Travis.

The release task does not support this, because it always pushes `grgit.branch.current.fullName`.

My workaround so far is to add `git checkout $BRANCH` to the [CI config](https://github.com/tschulte/gradle-semantic-release-plugin/blob/v1.1.1/.travis.yml). This workaround does not work however, if I want to rebuild a tag using the `RebuildVersionStrategy` (because e.g. upload to nexus failed and it should be retriggered).

The plugin should allow building in detached HEAD state by auto-detecting if it is run in detached HEAD state.

**Comment by ajoberstar** [comment]
I don't use detached heads often. In that scenario what should the plugin do? Would it skip the push of the branch and just push the tag?
