### ISSUE TITLE
NearestVersionLocator reports the wrong distances

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/gradle-git#139]
The `NearestVersionLocator` performance improvements have changed the commit counts returned as distance. This should be consistent with `git describe`.

**Comment by shradej1** [comment]
![screen shot 2015-10-13 at 2 00 40 pm](https://cloud.githubusercontent.com/assets/220345/10463479/e8980d84-71b2-11e5-8048-df48bedf1577.png)

With the default release-opinion settings, printing the version on master with 1.3.1 reports 1.1.0-rc-1.dev.1+50f8690, while git describe reports 1.1.0-rc-1-3-g50f8690.  Version 1.2.0 of gradle-git reports the same as git.  I suppose a workaround would be to define a new version locator that uses git describe directly, with the --match option.

**Comment by ajoberstar** [comment]
I'll see if I can write a test based on that graph you provided that recreates this issue.

**Comment by ajoberstar** [comment]
I think I've reproduced the issue, and it seems related to the order the commits are being traversed in, with it showing the issue you have when a merge commit is involved. Unfortunately, I think it's going to take another rewrite of the locator.
