### ISSUE TITLE
Update wiki with instructions to install using plugins mechanism

### ISSUE THREAD

**Issue by nigelcharman** [ajoberstar/gradle-git#140]
It would be useful to show the new plugins mechanism on the wiki for usage with Gradle 2.1+. For example, the github-pages plugin can be installed using:

    plugins {
      id "org.ajoberstar.github-pages" version "1.3.1"
    }

rather than using the lengthier `buildscript` and `apply plugin` sections.

**Comment by ajoberstar** [comment]
Good call. I'll update those right now.

**Comment by nigelcharman** [comment]
Thanks. I've just made some further updates to your changes:

https://github.com/ajoberstar/gradle-git/wiki - add "Gradle 2.1 or later" to plugin portal dependency
https://github.com/ajoberstar/gradle-git/wiki/org.ajoberstar.github-pages and https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins%201.x - state that the additional configuration is only needed for "classic" plugin dependency.

**Comment by ajoberstar** [comment]
Thanks!
