### ISSUE TITLE
publishGhPages fails silently if gh-pages branch does not already exist

### ISSUE THREAD

**Issue by jdigger** [ajoberstar/gradle-git#141]
I've spent may hours tracking this down, since there's no logging at all and no errors are raised, but the `prepareGhPages` task successfully preps everything.

Ideally `publishGhPages` would auto-generate the branch, but at the very least it should give **_some_** indication (like failing) that it wasn't able to check out the `gh-pages` branch.

**Comment by ajoberstar** [comment]
Definitely should provide some output. Per #74, I don't think there's a way to create it as a disconnected branch (which would be the ideal state), but an actual error is warranted

**Comment by hierynomus** [comment]
@ajoberstar From what I just gathered, it is possible to create an [orphaned branch](http://download.eclipse.org/jgit/site/3.7.0.201502260915-r/apidocs/org/eclipse/jgit/api/CheckoutCommand.html#setOrphan(boolean)) using JGit. So it should be possible.

**Comment by ajoberstar** [comment]
Interesting, l must have missed that when looking into #74. I'll probably pursue that as the solution instead of the error approach. Thanks for finding that!
