### ISSUE TITLE
run task based on commit

### ISSUE THREAD

**Issue by dmodoomsirius** [ajoberstar/gradle-git#144]
Is there a way to run a task based on a github commit?

**Comment by ajoberstar** [comment]
This may work, depending on your use case. You could have the task's `onlyIf` check for the text in the commit message. If that passes the body of the task would run. Something like:

```groovy
task doStuff {
  onlyIf {
    grgit.log().find { it.message.contains('the word') }
  }
  doLast {
    // do your other grgit stuff
  }
}
```

**Comment by dmodoomsirius** [comment]
http://build.endermedia.com/browse/BBM-VED-159 having this issue I even did a import org.ajoberstar.grgit
https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/build.gradle. Any clues?

**Comment by ajoberstar** [comment]
The `grgit` property is added to your project by a plugin. This should work if you add:

```groovy
apply plugin: 'org.ajoberstar.grgit'
```

**Comment by dmodoomsirius** [comment]
I am having this error

    version = 1.7.10-0.6.11b20151104194011
    version = 1.7.10-0.6.11b20151104194011
    Current Minecraft version = 1.7.10-10.13.3.1428-1.7.10
    Current Minecraft version = 1.7.10-10.13.3.1428-1.7.10
    Current Java version = 1.7.0_79 (Oracle Corporation 24.79-b02)
    Current Java version = 1.7.0_79 (Oracle Corporation 24.79-b02)
    ****************************
     Powered By MCP:             
     http://modcoderpack.com/    
     Searge, ProfMobius, Fesh0r, 
     R4wk, ZeuX, IngisKahn, bspkrs
     MCP Data version : unknown
    ****************************
    Found AccessTransformer in main resources: VE_at.cfg
    :curseTest FAILED
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file 'C:\Users\Admin\Desktop\MC\Minecraft\Git\Github\BBM\VoltzEngine\build.gradle' line: 100
    
    * What went wrong:
    Could not evaluate onlyIf predicate for task ':curseTest'.
    > No such property: message for class: org.ajoberstar.grgit.Commit
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more     log output.
    
    BUILD FAILED
    
    Total time: 28.766 secs

**Comment by ajoberstar** [comment]
Sorry, I gave you the wrong property name on [Commit](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/Commit.html). Should be `fullMessage` instead of `message`.

**Comment by dmodoomsirius** [comment]
Its fine I want to thank you very much for your help.

**Comment by ajoberstar** [comment]
No problem. Glad it's working for you.

**Comment by dmodoomsirius** [comment]
for checking commits would 
``` 
grgit.log().find { it.fullMessage.contains("[deploy]") }
```
work?

**Comment by ajoberstar** [comment]
Yep that logic should work.

**Comment by dmodoomsirius** [comment]
now because of the way i have the build script apparently http://build.endermedia.com/browse/BBM-VED-163 happens on https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/build.gradle#L98-L109

**Comment by ajoberstar** [comment]
Not sure if that build output you linked to matches up with the `build.gradle` anymore. I assume you've made changes since then?

**Comment by ajoberstar** [comment]
Feel free to reopen if you want to continue pursuing this. I'd need a fresh link to build output and build.gradle that match up.
