### ISSUE TITLE
Seems like grgit is always getting a cached version from the git repo

### ISSUE THREAD

**Issue by ymolists** [ajoberstar/gradle-git#146]
Hi All.

If i checkin something in git it is not getting picked up by grgit ? For example i am able to clone everything that was checked in yesterday. So i always get an old version from git when i use grgit.

When i clone the same repo from the git command line i always get the latest. Is there something in grgit that is caching ? or forcing me to get an old sha ?

Here is the code i use to clone the repo from gradle:
```gradle
        doLast {
            def targetRepo = file(mod_def.buildPath)
            if(!targetRepo.exists()) {
                def repFile = file(mod_def.buildPath);
                def repGit = Grgit.clone(dir: mod_def.buildPath, uri: "git@${git_repHost}:${mod_def.gitRep}")
            } else {
                println "pulling remote repo $mod_def.buildPath"
                //def gitRepo = Grgit.open(dir: mod_def.buildPath)
                //gitRepo.pull()
            }            
        }
```

**Comment by ajoberstar** [comment]
It would surprise me if there's anything cached (definitely not by Grgit and highly unlikely by JGit).

My best guess is that your remote isn't using a branch named `master` as its "default". Grgit's [CloneOp](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/CloneOp.html) uses an explicit default of `master` for `refToCheckout`. You'll need to override that if `master` isn't what you're expecting.

**Comment by ymolists** [comment]
Thanks ... it was all in my scripts ... sorry about this and thanks !
