### ISSUE TITLE
Problem using ssh-agent

### ISSUE THREAD

**Issue by alrighttheresham** [ajoberstar/gradle-git#147]
Hi Andrew, I've configured gradle-git to push content to gh-pages on a private repo.  My private repo access is managed via ssh-agent.  When I run publishGhPages, I get the following error. 

gradle publishGhPages
:docs:prepareGhPages FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs:prepareGhPages'.
> Problem cloning repository.

Running with --info I get 
...
The following authentication options are allowed (though they may not be available): [HARDCODED, INTERACTIVE, PAGEANT, SSHAGENT]
using interactive credentials, if needed
ssh-agent available
not using agent proxy: no identities found
...

However git pull works fine (using the appropriate identity).

git pull
All keys already loaded
Already up-to-date.

Any ideas what maybe happening?

**Comment by alrighttheresham** [comment]
gradle -v

------------------------------------------------------------
Gradle 2.6
------------------------------------------------------------

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Mac OS X 10.11.1 x86_64

And 

id 'org.ajoberstar.github-pages' version '1.3.2'

**Comment by ajoberstar** [comment]
I'm wondering if `git` is doing something different to look for keys. That message "All keys already loaded" seems to be from a command `ssh-ident` (some [reference here](https://github.com/ccontavalli/ssh-ident/issues/5)).

When you say `git pull` works when "using the correct identity", what are you doing to get the identity loaded? Are you doing that same step before calling `gradle publishGhPages`? Can you also run `ssh-add -l` before running Gradle to confirm that the identity is loaded?

**Comment by alrighttheresham** [comment]
Hi Andrew, yes I'm using ssh-ident to manage my keys.  This seems to be where the problem is.  

ssh-add -l
The agent has no identities.
➜  functional-specification git:(master) ✗ git pull
Loading keys:
    /Users/xxxx/.ssh/identities/personal/id_rsa
Enter passphrase for /Users/xxxx/.ssh/identities/personal/id_rsa:
Identity added: /Users/xxxx/.ssh/identities/personal/id_rsa (/Users/xxxx/.ssh/identities/personal/id_rsa)
Lifetime set to 7200 seconds
Already up-to-date.
➜  functional-specification git:(master) ✗ ssh-add -l
The agent has no identities.
➜  functional-specification git:(master) ✗

Sorry for the hassle.
