### ISSUE TITLE
If the tagStrategy.prefixNameWithV is set to false generated message prints entire history for each release

### ISSUE THREAD

**Issue by sdavids13** [ajoberstar/gradle-git#149]
https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/OpinionReleasePlugin.groovy#L67

Previous version is hard-coded with a "v" prefix and doesn't actually take into account tagStrategy.prefixNameWithV setting thus the previous tag is never found and the history is not trimmed resulting in the entire repo history being printed for every release.

**Comment by ajoberstar** [comment]
Sorry for the delay. My rationale was that the "opinionated" plugin didn't need to take into account different configuration, however I can see how that's a pain in this situation.

This one's not high on my priority list, but I would take a pull request.

**Comment by sdavids13** [comment]
Opened new PR: https://github.com/ajoberstar/gradle-git/pull/152

**Comment by ajoberstar** [comment]
Nice turnaround. Thanks!
