### ISSUE TITLE
Issue while building with gradle

### ISSUE THREAD

**Issue by svverma** [ajoberstar/gradle-git#151]
Hi, I am new to learning gradle. I want to create tags in git using gradle plugin . when I build this project with gradle, I am getting some issue like 'Repository not found' and its pointing towards build.gradle where plugins id for git gradle plugin. I am not able to figure out how to remove. Can anybody help!

**Comment by ajoberstar** [comment]
Repository not found would imply that you tried to open a Git repository that doesn't exist. (possibly by directly using `Grgit.open`)

Do you have more specifics on what you are doing in your build.gradle? Posting a snippet or the entire `build.gradle` would be most helpful to get a resolution.

**Comment by svverma** [comment]
Well, I have imported exactly the same code here in. No changes. It says repository not found and points to the plugin id.

**Comment by ajoberstar** [comment]
Sorry if I'm misunderstanding, but are you saying you copied the source of `gradle-git` and when running gradle it fails with "repository not found"? If so, did you clone the git repo, or just download the archive? I'm pretty sure that my build won't work unless it's in a git repo.

**Comment by svverma** [comment]
Yes, that was the issue. Thanks :)

**Comment by ajoberstar** [comment]
No problem.
