### ISSUE TITLE
Issues applying plugin to a subproject of a hierarchical build if the root project isn't versioned

### ISSUE THREAD

**Issue by dljsjr** [ajoberstar/gradle-git#154]
Hey there,

I'm trying to introduce some simple git tagging functionality in to our Maven-type publications. Our developers often work across several repos simultaneously, and we have a workflow in place where a developer will have a tool-generated and unversioned Gradle root project on their disk that contains all of our repos (which are gradle projects) as a subproject to this root project.

Applying the plugin inside a subproject and then running gradle commands from the command line within the subproject is fine. However, if gradle is initiated in the root project directory (where the plugin is *not* applied, just for clarity), the build fails with the following output:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dstephen/Developer/Workspaces/IHMC/AllCode/IHMCOpenRoboticsSoftware/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version: '1.4.0-rc.1']
> Failed to apply plugin [id 'org.ajoberstar.grgit']
   > One of setGitDir or setWorkTree must be called.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.602 secs
```

So to clarify:

1.) I have a root project, AllCode. Its build.gradle is empty, it just serves as an anchor root project. It is not under version control.
2.) There is a subproject in AllCode, in this example called IHMCOpenRoboticsSoftware, that is under version control. The build.gradle for this project applies the plugin via the plugin portal:
```
plugins {
    id 'org.ajoberstar.grgit' version '1.4.0-rc.1'
}
```
3.) When running Gradle from within the root project, the build fails at the plugin application stage. Everything works as expected when running Gradle from within the subproject

This has some other annoying side effects, one of them being that it becomes impossible to import the whole project collection in to an IDE as a single unit.

**Comment by dljsjr** [comment]
My current workaround for this is to add a `buildscript` block and add the plugin as a classpath dependency without applying the plugin instead of using a plugin block.

There could be two fixes here; one is to suggest what I said as a workaround but I think a better fix could be to change the plugin behavior to use `project.projectDir` instead of `project.rootProject.rootDir` in apply.

**Comment by ajoberstar** [comment]
Hi Douglas. The `org.ajoberstar.grgit` is based on the assumption that the boundaries of your Git repo match the boundaries of your Gradle "build" (i.e. all projects within the current build). I'd have to see some more counter-examples to understand whether the flexibility to apply this to individual projects overrides the benefits of getting a single `Grgit` instance tied to the root in all of your projects. I wouldn't want to open a fresh `Grgit` instance for each of those, in the case of multi-project builds that are actually in the same repo.

Assuming the following is your current workaround, I would lean towards continuing to use it:

```
buildscript {
  classpath 'org.ajoberstar:gradle-git:1.4.0-rc.1'
}
ext.grgit = Grgit.open(currentDir: projectDir)
```

**Comment by dljsjr** [comment]
That's what I'm currently doing, yes, and it does work. I can definitely see the argument from both sides. I don't have very strong feelings about it, so feel free to close as a wontfix.

**Comment by aksel-filipovic** [comment]
It works even better if using: ext.grgit = Grgit.open(currentDir: rootDir), bcause it shows the root of the gradle multimodule project.
