### ISSUE TITLE
+ sign in dev/default strategy as part of the semantic version ([+<build metadata>]) can be problematic in some integration test scenarios...

### ISSUE THREAD

**Issue by prokod** [ajoberstar/gradle-git#155]
Hi,

When using org.ajoberstar.release* plugin and while running tests locally the added + sign to the constructed jar interferes with loading of the jar from build/libs dir by some test frameworks. the + sign is considered reserved in some of them and it is being converted to a space - hence the jar is not found - hence the test fails.

Is there a way to configure it ? any advice on dependsOn rules to mitigate it?

**Comment by prokod** [comment]
Ok,

I figured it out ...
I used defaultVersionStrategy = Strategies.SNAPSHOT.
It seems to me the defaultVersionStrategy should be set from "factory" to SNAPSHOT strategy IMHO.

Maybe adding to README what will be the output "flavour" for each provided strategy will help users.

Thank you.
Noam

**Comment by ajoberstar** [comment]
*Regarding SNAPSHOT as a default...* The `opinion` plugin is intentionally named to indicate that it's my view of the preferred configuration. Though I'm aware those defaults can be cumbersome in situations, I'm not personally a huge fan of snapshots. You do have the option to use the `base` plugin and configure it entirely to your preferences if you don't want any of that baggage though.

*Regarding the documentation...* The usage stuff is all in the wiki, but really isn't in the best shape. I am curious if it's a formatting/exposure issue or actual missing content. Would you mind taking a look at these two docs ([release plugins](https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins%201.x) and [semver support](https://github.com/ajoberstar/gradle-git/wiki/SemVer%20Support)) and letting me know what you think could be improved?

**Comment by prokod** [comment]
Hi, so I went over release plugins doc which seems to me the first one users should look at when they try to search for info about release plugin.

I think the document should give more emphasise on usage with code examples. So under usage there should be: Adding the plugin to your project ; Configuring ; Cutomizing.
I think the fact that the a strategy can be customized is a great feature which should have some more exposure. For instance an example on how to change the default strategy to have a different sign before the build metadata part.

**Comment by ajoberstar** [comment]
Thanks for reviewing that! I'll plan to make some clarifications to the docs along the lines of what you suggested.

The sign before the build metadata isn't configurable in order to match the [SemVer spec](http://semver.org), so that is unlikely to change.
