### ISSUE TITLE
Could not find property 'GitClone' on project

### ISSUE THREAD

**Issue by huaxiaogood** [ajoberstar/gradle-git#157]
Hi ~

I found this error in my project

![image](https://cloud.githubusercontent.com/assets/8043228/12772907/3bbb3128-ca71-11e5-8147-37058604fb43.png)

task cloneLibraryGitRepo(type: GitClone) {
    def destination = file("../libraryTest")
    uri = "https://myurl.git"
    destinationPath = destination
    bare = false
    enabled = !destination.exists() //to clone only once
}

How can I solve this ? Thanks

**Comment by ajoberstar** [comment]
What version of `gradle-git` are you using? It's been quite a while since those tasks were removed. In a current version, you should be able to do something like this:

```groovy
task cloneLibraryGitRepo {
  doLast {
  Grgit.clone(dir: file('../libraryTest'), uri: 'https://myurl.git')
  }
}
```

See [Grgit Usage](https://github.com/ajoberstar/gradle-git/wiki/Grgit%20Usage)

**Comment by huaxiaogood** [comment]
my version is 1.4.1~let me try what you told me above~

**Comment by huaxiaogood** [comment]
But……when i build my project,nothing happens =.=

**Comment by ajoberstar** [comment]
Do you have any output you can post? Please include the Gradle command you executed.

**Comment by huaxiaogood** [comment]
![image](https://cloud.githubusercontent.com/assets/8043228/13065260/a4fe761c-d495-11e5-9f8e-11b80545e65d.png)

i use the command：“gradlew cloneLibraryGitRepo”

**Comment by ajoberstar** [comment]
You'll need an import for Grgit:

```
import org.ajoberstar.grgit.Grgit
```

**Comment by huaxiaogood** [comment]
Thanks! Success! :+1: :100:

**Comment by huaxiaogood** [comment]
But i found another issues,the repo i cloned is not the newest.It looks like the earliest master branch
