### ISSUE TITLE
automatically update the module

### ISSUE THREAD

**Issue by bihaitian** [ajoberstar/gradle-git#160]
hello，After I watched this plug-in think writing is very good, but use method does not understand，
Is this can solve this problem？
the problem is  
When loading the project how to automatically update the module, the module is independent on the git project

**Comment by ajoberstar** [comment]
By module are you referring to git's submodule feature? If so, there currently isn't any submodule support in [grgit](https://github.com/ajoberstar/grgit). You can file an issue there if you'd like to request additional features around that.

If you're not referring to submodules could you clarify what your use case is?
