### ISSUE TITLE
Multiple components per git repo

### ISSUE THREAD

**Issue by ieugen** [ajoberstar/gradle-git#161]
Hello, 

I have a multi module gradle project with the following structure:
````
- my-project
  - commons - constants, interfaces, etc
  - database - database bindings used by the upper modules
  - client1-api - depend on database and commons
  - client2-api - same as above
  - client3-api - same as above
```` 

I would like to have a release per module and keep all the versions in the same git repo. It makes to keep the module in the same repo since all of them are very closely related but also have different life cycles that it makes sense to have different versions and different release cycles. 

I think this use case is quite doable by configuring each project to get the version via a custom Tag parser. Ex:
_commons_ should get the version from tags that start with commons: commons-0.2.3, commons-x.y.z . The same should be available for the other modules: database gets version from tags like database-3.4.2 or db-0.2.3 .

One imported note is that not all of these projects are Java. Some are nodejs. I build a distribution out of the different release versions and deploy that artifact. 

Is this something are you taking into consideration/ open about having merged ?

I'm using gradle-git and it has made my life better. Thank you for all the work.

**Comment by ajoberstar** [comment]
I don't think I would want to merge that in, as I'm more of the opinion that there shouldn't be multiple release cycles within a repository. However, I do think it makes sense to make sure you have the building blocks to do that, if you want/need to. If there are some changes needed to make that possible, I would be willing to merge those.

One possible issue is the behavior that the same version is applied to all projects. Maybe that just needs to be decoupled from the other parts of the behavior.

**Comment by ieugen** [comment]
Thanks, I'll look into it as time allows me to. I've tried once and I didn't end far. My gradle developer skils are at beginner level.

**Comment by ieugen** [comment]
I moved to multtiple repositories. This use case does not work with git-flow. It's much more easier to reason and manage multiple repos.
