### ISSUE TITLE
No such property: inferredVersion for class: java.lang.String

### ISSUE THREAD

**Issue by jdesmet** [ajoberstar/gradle-git#162]
Please [refer here for commit point and line](https://github.com/ajoberstar/gradle-git/commit/53e88f4c788ecfa0b13b02678388b0e93bbeca22#commitcomment-16258851). 

I get below error when running a `snapshot` task with the `nebula-release` plugin.

    Caused by: groovy.lang.MissingPropertyException: No such property: inferredVersion for class: java.lang.String
           at org.ajoberstar.gradle.git.release.base.BaseReleasePlugin$_addReleaseTask_closure4_closure6.doCall(BaseReleasePlugin.groovy:90)

Why is `.inferredVersion` being called here on a String (`project.version`)? `project.version` is known to be a string (and it is in my case)?

**Comment by ajoberstar** [comment]
Gradle allows the `project.version` to be any `Object`. The `BaseReleasePlugin` sets the version using [this extension](https://github.com/ajoberstar/gradle-git/blob/53e88f4c788ecfa0b13b02678388b0e93bbeca22/src/main/groovy/org/ajoberstar/gradle/git/release/base/ReleasePluginExtension.groovy#L44) to an object that does have an `inferredVersion` property.

I'm not familiar with the specific behavior `nebula-release` adds, but you shouldn't be overriding the `project.version` property when you use either `org.ajoberstar.release-base` or `org.ajoberstar.release-opinion`.

**Comment by jdesmet** [comment]
Thanks. That largely answers the question. I think I am missing a lot of (getting started) documentation. I was wondering how the version was maintained. Although I understood that version is inferred by the branch name or tag, I still thought that it somehow 'modified' files etc the way it happened in maven. 

Anyway, I am moving away from maven, and am more interested in following a [branch-centric develop-release cycle in Git](http://nvie.com/posts/a-successful-git-branching-model/). Gradle seems to be the right way to go, but right now I am having a little trouble getting my first project converted over. Even selecting the right set of plugins to execute the release is still going to keep me busy for a while.

Thanks for your good work - seems like you have contributed a lot.

**Comment by jdesmet** [comment]
Ok - I can remove the hardcoded version - that is fine. But now I am on the `develop` branch and want to do a snapshot release. In that case, how is the version inferred? I assume the first time around, I could supply a parameter overriding it, then what about the next times?

**Comment by ajoberstar** [comment]
I can't speak for the other plugins, but I'd point you to [this doc for usage of gradle-git](https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins%201.x). That should help explain what this plugin will do. Ultimately, it's just using the tags in your history to infer the version. It won't inherently do anything to help you utilize git flow, however it can work along with that.
