### ISSUE TITLE
Opening a dynamic path

### ISSUE THREAD

**Issue by atomicpages** [ajoberstar/gradle-git#163]
Wondering how I can open my resources path (which contains a git repo). Here's what I have:

~~~groovy
def grgit = Grgit.open(dir: this.getClass().getResource("grammars").toString())
~~~

But I'm getting this error:

<img width="514" alt="screen shot 2016-03-06 at 10 30 11 pm" src="https://cloud.githubusercontent.com/assets/1824291/13562234/0e006e0e-e3eb-11e5-9725-70f449868b55.png">

I poked around some [in the docs](http://ajoberstar.org/grgit/docs/groovydoc/index.html?org/ajoberstar/grgit/Grgit.html) and I'm basing it off this example:

~~~groovy
def grgit = Grgit.open(dir: 'some/dir/path')
~~~

Being that the repo is nested in my resources folder, I need a way to access it dynamically without using the deprecated `Grgit.open(java.io.File, Credentials)` method.

**Comment by ajoberstar** [comment]
The non-deprecated `open` method is dynamic (using the Groovy MOP) like most of the methods in Grgit. This looks like an Intellij warning, but I can't see from what you included if it treats it as an error or not. You really should be fine to call it the way you posted.

**Comment by atomicpages** [comment]
@ajoberstar, thanks for reply! I'm too versed in Gradle or Groovy so all this is fairly new to me. But I'm getting a host of other, and perhaps more critical, issues. If you can help me, I'd appreciate it immensely! 

**build.gradle**

~~~groovy
import org.ajoberstar.grgit.Grgit

group 'org.java-grader'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'maven'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.google.code.gson:gson:2.6.2','com.github.javaparser:javaparser-core:2.3.0',
		    'net.sourceforge.argparse4j:argparse4j:0.7.0', 'org.mockito:mockito-core:2.0.33-beta',
		    'commons-io:commons-io:2.4', 'com.google.guava:guava:19.0', 'com.puppycrawl.tools:checkstyle:6.16',
		    'org.antlr:antlr4-master:4.5.2-1', 'org.ajoberstar:gradle-git:1.4.2'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

def grgit = Grgit.open(dir: this.getClass().getResource("grammars").toString())

task updateGrammars << {
	grgit.pull()
}
~~~

```log
Error:(1, 0) Cause: startup failed:
build file '/Users/dennis/Documents/Development/java/java-grader/build.gradle': 1: unable to resolve class org.ajoberstar.grgit.Grgit
 @ line 1, column 1.
   import org.ajoberstar.grgit.Grgit
   ^

1 error
```

Getting this error when attempting to refresh Gradle in IntelliJ so I can see/test the task. I'm really new to build systems in general so I'm not sure how to resolve this error.

**Comment by ajoberstar** [comment]
Sure, no problem. It looks like you're just missing the dependency on the plugin itself. Try looking at [this wiki page](https://github.com/ajoberstar/gradle-git/wiki) which shows how you declare that piece.
