### ISSUE TITLE
Add support for Heroku

### ISSUE THREAD

**Issue by balteo** [ajoberstar/gradle-git#164]
Hi,
It seems the gradle git plugin does not work with Heroku (the gradle buildpack). The plugin works a charm locally but when I deploy my app on Heroku through github I get this:

```
Execution failed for task ':bignibou-server:generateGitProperties'.
       > org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /tmp/build_4554f9f0f404781365e453846c38e499/silteo-bignibou-site-ad93e406ac8e613a615778d617498dd057043ace
```

**Comment by ajoberstar** [comment]
Can you provide more information about what your `generateGitProperties` task does? I'm guessing there's just some different config you'll want to use to make sure you point at the right repo directory.

**Comment by balteo** [comment]
I am sorry. It seems this issue is more relevant to the following project: **gradle git properties**. I have opened an issue there: https://github.com/n0mer/gradle-git-properties/issues/10

**Comment by ajoberstar** [comment]
Not a problem
