### ISSUE TITLE
how to update release notes and load war/binaryfiles to a tag in github

### ISSUE THREAD

**Issue by muralidcis** [ajoberstar/gradle-git#167]
@ajoberstar 
 Iam currently trying to create a new and add release notes to the body, add a war/file. Typically the release_name,release_body,form-control filename,release_prerelease 

// Create the tag 
`grgit.tag.add(name: tagName, message: "Addition of new tags for toolkit release  `${tagName}",force:true,  annotate: true)`
   
Kindly suggest me how to upload the release notes to body and upload war to the the release.

**Comment by ajoberstar** [comment]
Hi,

It sounds like you're trying to create a Github release. Is that correct? I don't currently have any support for the Github APIs, just interacting with Git itself.

**Comment by muralidcis** [comment]
@ajoberstar  Thanks, for responding to me, you are right, iam trying to wrap the release notes and generated war to the existing taged version of github release. well will figure out an the ways.
