### ISSUE TITLE
Help needed: Not able to remove tags from remote

### ISSUE THREAD

**Issue by muralidcis** [ajoberstar/gradle-git#168]
@ajoberstar 

With the following code iam able to remove the tag form local but not from remote. kindly help me out.
```
grgit.tag.remove(names: [tagName])

task removeTag <<{  
    def tagName = getVersion()  
    println 'removing tag '+tagName  
    grgit.tag.remove(names: [tagName])  
    grgit.push(tags: true) 
}
```

**Comment by ajoberstar** [comment]
I think you have to do this similar to how you might on command line Git:

**CLI Git:**

```
git push origin :tagName
```

**Grgit:**

```
grgit.push(refsOrSpecs: [':tagName'])
```

**Comment by muralidcis** [comment]
I tried it, and still its the same... 
`classpath 'org.ajoberstar:gradle-git:1.4.0'`

`task removeTag <<{`
`    def tagName = getVersion()`
`    println 'removing tag '+tagName`
`    grgit.tag.remove(names: [tagName])`
`    grgit.push(refsOrSpecs: [':tagName'])`
`}`

Here follows the info:
Tasks to be executed: [task ':removeTag']
`:removeTag (Thread[main,5,main]) started.`
`:removeTag`
`Executing task ':removeTag' (up-to-date check took 0.001 secs) due to:`
`  Task has not declared any outputs.`
`Starting process 'command 'git''. Working directory: /home/murali/GITHUB/gradle-gitpush-upload-release Command: git describe --tags`
`Successfully started process 'command 'git''`
`removing tag 9.9.2`
`The following authentication options are allowed (though they may not be available): `[PAGEANT,` `HARDCODED,` `SSHAGENT, `INTERACTIVE]`
`using hardcoded credentials` `from system properties`
`:removeTag `(Thread[main,5,main])` `completed. Took 3.324 secs.`

**Comment by ajoberstar** [comment]
What do you mean by the draft?

**Comment by muralidcis** [comment]
I mean the release draft, where we added the release notes an upload the war to it.

**Comment by ajoberstar** [comment]
OK, that would be Github specific. Right now, I don't have anything integrating with Github.
