### ISSUE TITLE
Need help using github-pages to publish JDiff HTML.

### ISSUE THREAD

**Issue by noel-yap** [ajoberstar/gradle-git#169]
The documentation for github-pages is pretty sparse. How do I use it to point to a directory that contains a bunch of HTML?

Thanks,
Noel

**Comment by ajoberstar** [comment]
Definitely sparse, I'm making some big assumptions about Gradle knowledge. The `pages` element in the extension is a standard Gradle [CopySpec](https://docs.gradle.org/current/javadoc/org/gradle/api/file/CopySpec.html) (you can also see the `Copying Files` subsection of the [Working with Files](https://docs.gradle.org/current/userguide/working_with_files.html) chapter in the Gradle user guide).

Something like this should cover your use case:
```
githubPages {
  // ...
  pages {
    from 'some/dir/relative/to/project'
  }
}
```
