### ISSUE TITLE
Improve messaging when strategies are skipped

### ISSUE THREAD

**Issue by javajon** [ajoberstar/gradle-git#175]
Searching GitHub people are using a combination of Strategies like this:

```
release {
    grgit = new OpenOp(dir: '.').call()

    versionStrategy Strategies.FINAL
    versionStrategy Strategies.PRE_RELEASE
    defaultVersionStrategy Strategies.DEVELOPMENT
}
```

With: gradlew build 
the jar produced has a developer formatted version as expected by the default versing strategy.

With:./gradlew release -Prelease.scope=major -Prelease.stage=final
the error message "Stage final is not one of [dev] allowed for strategy development." is presented.

How can these Strategies work together?

**Comment by javajon** [comment]
By adding 

`println "Repository is " + (grgit.status().isClean() ? "clean." : "not clean.")`

to the above release block this helped show the problem.  As documented the FINAL and PRE_RELEASE Strategies will be ignored if the repository is dirty.  Thus, it fell to the DEVELOPMENT Strategy which did not understand 'final' for the Stage.  Once the local changes were git committed the FINAL and PRE_RELEASE Strategies accepts their associated Stages.

For newbies perhaps this error message would add clarity 

Stage final is not one of [dev] allowed for strategy development.  Strategies X, Y, Z, ignored stage final since the repository is not clean.

**Comment by ajoberstar** [comment]
Yeah, the default message can be a little confusing. If you turn on the `--info` level logging it tells you each strategy that was skipped. I'll have to see if/how a more helpful message could be generated.
