### ISSUE TITLE
A cause and effect table to illustrate tag & git state & scope & stage & Strategy -> Result

### ISSUE THREAD

**Issue by javajon** [ajoberstar/gradle-git#176]
Our team is adopting this great Gradle plugin.  In documenting it internally we came up with a table of scenarios to illustrate how the various scope and stage settings along with git state and applied Strategies generate the resulting version.  Perhaps if you had some form of this in the wiki it would help people understand how powerful this plugin is especially when applying strategies.  This table could help simplify the concepts for new readers.  For example:

```
Latest tag | Master | State |  Gradle Command                      | Result

1.0.0	  No	         Clean	build	                                        1.0.1-dev.14+fbf8904
1.0.0.rc      No	         Clean	build	                                        1.0.1-rc.dev.1+fbf8904
1.0.0	  No	         NC   	build -Prelease.stage=final      (failure)
1.0.0	  No	         Clean	build -Prelease.scope=minor   1.1.0-dev.14+fbf8904
1.0.0	  No	         NC	        build -Prelease.scope=minor   1.1.0-dev.14.uncommitted+fbf8904
1.0.0	  Yes	         Clean	build	                                        1.0.0
```
 	 	 	 	 
Pardon the ASCII art.  Perhaps adding a Strategy column too.

**Comment by ajoberstar** [comment]
Thanks providing that table. I'll include or something like it when I revise the docs.

**Comment by ajoberstar** [comment]
I took a stab at one, while revising the rest of the doc (still in progress). But how does [this](https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins#example-usage) look? I tried to make it more of a walkthrough, but that might have just added too much duplication.

**Comment by javajon** [comment]
Andrew,

This table and the other updated documentation helped me communicate to my
team why this is such a helpful plugin for our pipeline.  You have done
some great work as an implementation solution for the idea of versioning
using version control tags.  It's great software as its simple in its
implementation but powerful in how it can help a team.  We are doing some
interesting things with microservices and I see this as a key part of our
continuous integration and delivery solutions.  Tonight we watched your
plugin do its "release" magic with our Gradle-based pipeline on Jenkins 2.

Much praise. Thank you!

- Jonathan

On Sun, Jun 5, 2016 at 8:28 PM, Andrew Oberstar <notifications@github.com>
wrote:

> I took a stab at one, while revising the rest of the doc (still in
> progress). But how does this
> <https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins#example-usage>
> look? I tried to make it more of a walkthrough, but that might have just
> added too much duplication.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ajoberstar/gradle-git/issues/176#issuecomment-223847416>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJBBvDjMNRmoSYBXqfa2vPKtz_O8pp4dks5qI2nLgaJpZM4Ibz-B>
> .
>



-- 

   - - Jonathan
   Jonathan JohnsonJava Specialist, Software EngineeringDijure, LLC
   <http://www.linkedin.com/in/javajon/>

**Comment by ajoberstar** [comment]
Thanks for that, and glad the plugin's of use!
