### ISSUE TITLE
Can`t use release-opinion in build file included by apply from

### ISSUE THREAD

**Issue by orzeh** [ajoberstar/gradle-git#178]
Suppose I have following build scripts:

````groovy
//main build.gradle
apply plugin: 'java'
apply from: 'version.gradle'
//....
````
````groovy
//version.gradle
import org.ajoberstar.grgit.Grgit
import org.ajoberstar.gradle.git.release.semver.SemVerStrategy
import org.ajoberstar.gradle.git.release.opinion.Strategies

buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
    	classpath 'org.ajoberstar:gradle-git:1.4.1'
	}
}

apply plugin: org.ajoberstar.gradle.git.release.opinion.OpinionReleasePlugin

release {
	grgit = Grgit.open(rootProject.file('.'))
	versionStrategy Strategies.FINAL
	defaultVersionStrategy = Strategies.SNAPSHOT

	tagStrategy {
		generateMessage = { version -> "My version: ${version.version}." }
	}
}
````

Because in included build scripts you have to use plugin`s class name rather than its id (see [this post](https://discuss.gradle.org/t/how-do-i-apply-a-plugin-to-a-project-from-a-shared-applied-gradle-file/7508/2)) this build will fail because of [this line](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/OpinionReleasePlugin.groovy#L52) of `OpinionReleasePlugin`. We should use class name there to fix it.

**Comment by ajoberstar** [comment]
Hi orzeh, I appreciate you taking the time to post this and provide a PR, though I disagree with this being a `gradle-git` bug.

Gradle has always treated "script plugins" (i.e. `apply from`) as a second class citizen. The thread you referenced was created 3 years ago, but that limitation has been present in Gradle from day one, so it doesn't seem they have an intention of fixing it (though Peter's post seem to imply that they don't have good options to fix it).

I consider the fully-qualified class names of my plugins to be implementation details and not something I guarantee maintaining between minor or patch releases. While this is less relevant in the internals that your PR changed, using the IDs there does emphasize that view.

I'm going to mark this as a won't fix, and close your PR. Sorry that I'm not being more helpful on this one. I do appreciate your time for submitting this.
