### ISSUE TITLE
Deprecate default version strategies

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/gradle-git#180]
As noted in #175, default strategies sometimes aren't actually able to be used as a "default", since their selector returning false also implies that trying to run infer will fail. This should print a warning and be slated for removal in 2.0.0.

**Comment by javajon** [comment]
In 1.5.0 and in these notes I think you are saying "defaultVersionStrategy" is removed (not deprecated).  Now "gradlew clean" fails with "No version strategies were selected."  

With this deprecation/removal if I set 
 -Prelease.stage=dev

The Gradle tasks resume working without error.  Is adding "=dev" this the workaround for this deprecation/removal?  For developers I do not want to have to tell them to add this.  For our CI pipeline we set it to "final", but I would like "dev" to default if not specified.  

with 1.5.0 what would be a good way to ensure "dev" is the default strategy?

**Comment by javajon** [comment]
The answer appears to be adding 

release.stage=dev

to Gradle's build.properties

then the command line (e.g. via Jenkins) can override the property with -Prelease.stage=final

**Comment by ajoberstar** [comment]
There was a behavior change meant to avoid some confusing error messages. It should work in any situation it worked before, unless I'm remembering wrong.

Can you let me know what strategies you have configured (including the default)?

**Comment by ajoberstar** [comment]
Hmm... yeah, I think you're right. The tests I added when changing the behavior didn't cover the reason the defaults were there in the first place, so now I don't think they really work as expected. I'll consider this a regression and open a new bug, this will be out as a 1.5.1 release, most likely this weekend.

**Comment by javajon** [comment]
We are using:

        versionStrategy Strategies.FINAL
        versionStrategy Strategies.PRE_RELEASE_ALPHA_BETA
        versionStrategy Strategies.DEVELOPMENT

and just adding to gradle.properties

release.stage = dev

This works just fine.  No need for defaultVersionStrategy as -P property makes sense as a command line override.
