### ISSUE TITLE
Rebuilding on another machine scenario - need version to be same as tag

### ISSUE THREAD

**Issue by javajon** [ajoberstar/gradle-git#183]
Our goal:  We have a tag of 1.0.22.  We would like to do a build (e.g. SonarQube) of an artifact with that version as defined in the git tag.  

With version 1.5.0 we have just these strategies set:
        versionStrategy Strategies.FINAL
        versionStrategy Strategies.PRE_RELEASE_ALPHA_BETA
        versionStrategy Strategies.DEVELOPMENT

Problem:  When we run "gradlew build"  which is in applying no stage we get an error: "No version strategies were selected."  When we run "gradlew build -Prelease.stage=final" we get a version with the bump patch number to 1.0.23.

In your wiki table of examples, there is a row that says:

Repo State: Rebuilding on another machine	
Latest tag version: 0.1.0-milestone.2	
Gradle command: build 
Inferred version: 0.1.0-milestone.2

This table does not mention the state of the "stage" or "strategy" so it's not clear to us how we can get a build with a version that just uses the tag,

Up to now we have "release.stage = dev" in our gradle.properties file for a defaulted stage and on Jenkins we just pass in release.stage = final.  Both dev and final always bump the patch to the next number.  

For some builds (e.g. gradlew -Prelease.stage=final build) we would like the version to be the same as the tag.

**Comment by ajoberstar** [comment]
There's a brief mention in the configuration section of [the wiki page](https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins) to the strategies included in the opinion plugin, which is what the table is based on. The one you'll need to add is the RebuildStrategy. That one applies if there's no stage or scope input, and the current HEAD is tagged with a version.

**Comment by javajon** [comment]
We added RebuildVersionStrategy to our stack (as there is no RebuildStrategy).
    release {
        versionStrategy RebuildVersionStrategy.INSTANCE
        versionStrategy Strategies.FINAL
        versionStrategy Strategies.PRE_RELEASE_ALPHA_BETA
        versionStrategy Strategies.DEVELOPMENT
    }

When we run: gradlew -Prelease.stage=final clean
we still get the error message: "No version strategies were selected."

(We used the task "clean" instead of "build" as the task is irrelevant and faster to test)

**Comment by ajoberstar** [comment]
You can't set scope or stage, otherwise it will skip the rebuild strategy. If you run with --info it will log out why different strategies were skipped.

**Comment by ajoberstar** [comment]
This is actually part of the reason the default strategies exist. There still needs to be some way to infer the version without having passed any extra input in. So rebuild would take over with no input and being on a tagged version, and the default takes over with no input not on a tagged version.

**Comment by javajon** [comment]
Can you review this test project?  I think this better illustrates the problem:

git clone http://bitbucket.org/javajon/gradlegittest.git
gradlew -Prelease.stage=final build

This is a minimal project that has a tag of 1.0.0.  Upon executing task "build", you will see it produces version 1.0.1, not the desired 1.0.0.

**Comment by ajoberstar** [comment]
Just submitted [a PR](https://bitbucket.org/javajon/gradlegittest/pull-requests/1/removing-stage-prop/diff) to illustrate rebuild working. The issue is that you can't provide a value for `release.scope` or `release.stage`, regardless of whether it's as a command-line argument or in the gradle.properties. The logic is that if you provide any input you're trying to influence the version being inferred.

```
./gradlew printVersion
:printVersion
2.0.0

./gradlew -Prelease.stage=dev printVersion
:printVersion
Inferred project: gradlegittest, version: 2.0.1-dev.0+f19a393
2.0.1-dev.0+f19a393
```

This also reinforces though that some type of default strategy or scope is still needed to allow developers to work without having to provide an extra argument to gradle. #182 is open to resolve this.

**Comment by javajon** [comment]
In learning this plugin that logic was not clear to me.  We shall await #182.

**Comment by ajoberstar** [comment]
Can you test 1.5.1-rc.1 to see if it fixes your issue?
