### ISSUE TITLE
Allow a default stage

### ISSUE THREAD

**Issue by guenhter** [ajoberstar/gradle-git#185]
HI,

since the defaultVersionStrategy behaviour has changed in 1.5.0 so that is not longer possible, to execute without setting the stage, I would appreciate it, if a default stage can be set, which is used in case no other stage is overritten with the usual parameter property `release.stage`.

The reason is simple: During development, we don't want to type `-Drelease.stage=SNAPSHOT` everytime we call gradle. 

regards

**Comment by ajoberstar** [comment]
Totally agree, I have this tracked as #182 so I'll close this as a duplicate.
