### ISSUE TITLE
Only clone GitHub Pages repo if not already cloned

### ISSUE THREAD

**Issue by mojavelinux** [ajoberstar/gradle-git#189]
For some sites, the GitHub Pages repository is large and takes considerable time to clone (on top of the time it takes to first delete it from disk). Currently, the prepareGhPages task removes the existing folder, then clones the repository anew each time. It would save a lot of time if this plugin only cloned the repository if not already cloned. 

Ideally, the prepareGhPages task would check to see if the workingDir already exists and is a git repository. If both of those are true, the task would merely fetch updates.

**Comment by mojavelinux** [comment]
I want to add that this also leaves room for the repository to be cloned by a separate process (perhaps as part of a build pipeline).

**Comment by ajoberstar** [comment]
This makes sense. Didn't do it before out of simplicity, but it's a good idea.

**Comment by mojavelinux** [comment]
I'll try to give this one a shot. I suspect we'll have some code review iterations as we try to decide the best approach. One thing is for sure. This should save the turnaround time for back-to-back deployments (since most CI tools have the ability to cache workspaces).
