### ISSUE TITLE
Relative destination directory on CopySpec is not relative

### ISSUE THREAD

**Issue by mojavelinux** [ajoberstar/gradle-git#192]
The relative destination directory on CopySpec is not relative, as documented. Instead, the absolute path is being concatenated to the absolute path of the working directory, leading to unexpected results.

This can be seen by using the following configuration:

```groovy
githubPages {
  // ...
  pages {
    from 'build/generated-site'
    into '.'
  }
}
```

The targetDir used to locate files to wipe out should match the workingDir. Instead, it is matching workingDir + workingDir.

**Comment by mojavelinux** [comment]
This bug manifests because of a lack of test. I will send a PR with a fix and a test.

**Comment by siordache** [comment]
Quick and dirty workaround untill your PR will be merged:
```
githubPages {
  pages.metaClass.getRelativeDestinationDir = {
    destPath ?: new File('.')
  }
  ...
}
```
