### ISSUE TITLE
Add option to disable push operation in GitHub Pages plugin

### ISSUE THREAD

**Issue by mojavelinux** [ajoberstar/gradle-git#194]
At times, you may want to commit the changes to the cloned repository, but not push those commits to the remote. Add an option on the extension to disable the push operation.

```
githubPages {
  // ...
  push = false
}
```

This option is particularly useful when a user is first setting up the plugin or in testing scenarios. You want to see that the changes were committed, but not modify the remote repository (or not fail the build because of lack of write permissions to the remote).

**Comment by ajoberstar** [comment]
A similar use case cropped up a while back that initiated the prepare/publish task split. This allowed you to verify that the correct files were copied without doing the rest. 

Rather than add a config option, I think it would be better to introduce a new task in between prepare and publish for the commit or move committing into prepare. That way the testing use case would be just running another task rather than having to change config.

Does that seem appropriate for your use?

**Comment by mojavelinux** [comment]
I could definitely get behind that. The main issue right now is that the commit and push are coupled. There's no way to get code to run between those two operations. As long as we can uncouple them, we'll have accomplished the goal.

I like the idea of moving the commit to a doLast block of prepareGhPages. It seems to make the most sense there and allows use of all the Gradle mechanics to wrap or disable publishGhPages. If you agree, I'd be happy to update the PR.

**Comment by ajoberstar** [comment]
Yeah, that sounds good.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
I've updated the PR. The only downside with this new approach is that now it's not possible to run a custom task before the add/commit happens (related to #190). Before, you could force an artificial copy operation, then run a task before publishGhPages that made updates to files in the workingDir. Now, the only thing that runs between the clone and the add/commit is the copy spec.

I see two options.

a) we could implement #190 to execute a task manually between doFirst and doList.
b) we could add a new task commitGhPages that runs between prepareGhPages and publishGhPages. The add/commit doLast would go on that task instead of prepareGhPages.

wdyt?

Regardless of what we decide, we can still move forward with merging this one, then take the next step as part of #190.

Perhaps what we could also do is not define a CopySpec if it's not configured in the extension. That way, there's no need to "fake" it.
