### ISSUE TITLE
Confusing release flags

### ISSUE THREAD

**Issue by itissid** [ajoberstar/gradle-git#200]
This is a readability issue. Not a bug.

I am using `-Prelease.stage` and `-Prelease.scope` to control version inference at the moment. However this feels a little odd for tasks that don't release but just use the version. This could be made a bit more clearer in the plugin(somehow)

For example, we use these flags to generate build artifacts and the release command for just generating the tag. These two don't happen in the same gradle command and infact on separate machines.

Its mostly naming that makes it look odd, however a separate project level closure something like  `versionInfer` provided by this plugin might make this more readable, albeit verbose for the user.

**Comment by ajoberstar** [comment]
Yeah, I agree they're not the most appropriate for their real purpose. For now, I'm not sure if I'll change them, at best there would be some alternate names and deprecation of these. Long-term I plan to separate version inference into its own plugin (in-progress in [semver-vcs](https://github.com/ajoberstar/semver-vcs)). The naming will be different there.

**Comment by ajoberstar** [comment]
I'll leave this to semver-vcs, rather than changing here.
