### ISSUE TITLE
test the publish artifact on maven local

### ISSUE THREAD

**Issue by kknd22** [ajoberstar/gradle-git#201]
any easy way to test various publish (release) on local maven local or have to using a real nexus/artifactory for testing?

**Comment by ajoberstar** [comment]
Maybe I'm not following what you're asking, but publishing of artifacts produced by your build is something that happens independently from this plugin. You may configure the `release` task to depend on a publish task, but this plugin doesn't provide any actual publishing capabilities (besides the github pages stuff).

**Comment by kknd22** [comment]
you  are right, these two are completely different things. please close it. thanks
