### ISSUE TITLE
Separate gh-pages into its own repo

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/gradle-git#203]
As suggested by @mojavelinux in #190, this plugin isn't specific to Github Pages, it just publishes to any remote Git branch. Additionally, it's independent from any other functionality in `gradle-git`, so there's no need to couple them.

**Comment by ajoberstar** [comment]
The existing plugin should remain until v2.0.0 of gradle-git for backwards compatibility.

**Comment by mojavelinux** [comment]
:+1:

**Comment by jnorthr** [comment]
+1 👍

**Comment by ajoberstar** [comment]
See [gradle-git-publish](https://github.com/ajoberstar/gradle-git-publish)

**Comment by mojavelinux** [comment]
:+1:

**Comment by siordache** [comment]
👍

**Comment by ajoberstar** [comment]
0.1.0 is out now of [gradle-git-publish](https://github.com/ajoberstar/gradle-git-publish).
