### ISSUE TITLE
not really an issue but more how to use the strategy correctly

### ISSUE THREAD

**Issue by kknd22** [ajoberstar/gradle-git#204]
Thanks for all the help so far. Almost get everything nailed down. Three more questions:  
1. Anyway to set `allowDirtyRepo=true` for all strategies?  (Jenkins build will create some temp files under the project during the build, that will cause the git consider repo is dirty - false alarm).  
2. How to start two parallel developments on the same scope (same major but different minor, or same major/minor but different patch).
Let's say `v1.9.0` is done and merged back to master. And development is on new major release. Now two branches `b1` and `b2` have been created from this point from master, `b1` and `b2` are planned for two parallel development, let's say
`b1`  ---> `v2.0.x`
`b2` --->  `v2.1.x`  
so for `b1` the release is easy: `-Prelease.scop=major -Prelease.stage=xxx` (will get v2.0.0.xxx)
what happen to `b2`?  unless `v2.0.x` tag (which might not be released yet from `b1`) is reachable from `b2`, it seems to has no way to infer, `-Prelease.scopr=major` will generate `v.2.0.0` not `v.2.1.0`?
And `-Prelease.scopr=minor` will even generate `v1.10.0` at this point. Either of them is the desired one.  
Thanks  
-cl

**Comment by ajoberstar** [comment]
1. Your best option is to add the paths to your `.gitignore`. 
2. This seems more along the lines of what #115 is meant to address. Your particular example isn't possible in the current world, because the version is always incremented from the last release, and you can only increment one of major/minor/patch by one.

**Comment by kknd22** [comment]
thanks
