### ISSUE TITLE
Support deploy_keys for authentication during ghPages pushes

### ISSUE THREAD

**Issue by eljobe** [ajoberstar/gradle-git#207]
I see from [Travis CI Authentication](https://github.com/ajoberstar/gradle-git/wiki/Travis-CI-Authentication), that you can use an auth token for your username when using the ghPages plugin.

However, as [this gist](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) points out:

> NOTE: an earlier version of this guide recommended generating a GitHub personal access token and encrypting that. Although this is simpler, it is not a good idea in general, since it means any of your repository's collaborators would be able to edit the Travis build script to email them your access token, thus giving them access to all your repositories. The repository-specific deploy key approach is safer.

It would be great if the ghPages plugin also supported some way to point to my private deploy_key which I have encrypted and decrypted using [Travis file encryption](https://docs.travis-ci.com/user/encrypting-files/).

I saw from the [grGit documentation](http://ajoberstar.org/grgit/docs/groovydoc/index.html?org/ajoberstar/grgit/auth/AuthConfig.html) that it should be sufficient to provide the `org.ajoberstar.grgit.auth.ssh.private=<path.to.private.key>` Java system property. But, even when running gradle with `-D` and this property, it doesn't work.

Here's my `build.gradle`: https://github.com/eljobe/gone-nomad/blob/master/build.gradle 
Here's my `.travis.yml`: https://github.com/eljobe/gone-nomad/blob/master/.travis.yml
Here's a link to the latest failing build: https://travis-ci.org/eljobe/gone-nomad/builds/146214512

Please let me know if I can be of any further assistance troubleshooting this issue.

**Comment by ajoberstar** [comment]
Could you run this build again with the `--info` argument, which should provide more information about what's going on. Does the key require a password? It may have found the key, but is now prompting to unlock it.

**Comment by eljobe** [comment]
The build *was* run with `--info`.
See Line 326: https://travis-ci.org/eljobe/gone-nomad/builds/146214512#L326

Did you mean I should run it with `--debug`?
https://travis-ci.org/eljobe/gone-nomad/builds/146296020
I don't see any additional useful information in that log either.

The gone-nomad_rsa deploy key is definitely not password protected. I was careful not to enter a password for exactly this reason. Also, I can `ssh-add gone-nomad_rsa` from my local machine and I am not prompted to enter a password.

Also, I'm not seeing any of the logger calls printed to the console. But, especially, not this one: https://github.com/ajoberstar/grgit/blob/8b6d5c3b692400bc3fb8f6fd078791838dd7870d/src/main/groovy/org/ajoberstar/grgit/auth/JschAgentProxySessionFactory.groovy#L109 which I would expect to see.

I don't think this is the case, but should I start the ssh-agent in my `.travis.yml` before calling gradle?
Another thing that occurs to me is that this machine might not have a `known_hosts` entry for `github.com`. But, that might not be a problem.

**Comment by eljobe** [comment]
I thought this might have had something to do with needing to already have an ssh-agent running. So, I added the commands to my `.travis.yml` in eljobe/gone-nomad@e9ae9ae

But, as you can see from the [latest failing log](https://travis-ci.org/eljobe/gone-nomad/builds/146452245#L187), it didn't help.

**Comment by eljobe** [comment]
Actually, feel free to close this issue. I'm going to move to some other CI infrastructure where I have more control.

**Comment by ajoberstar** [comment]
Looked closer at the original log and it did have the info messages, I just missed them when looking the first time around. Nothing super infromative though. Looks like there's nothing in the code that logs when the private key is added. So its hard to say what the issue is at this point without adding some more logging into the cod (which is probably worthwhile anyways).

Looks like you reopened, so let me know if you're still interested in looking into it.

**Comment by eljobe** [comment]
Sorry for the confusion. Only reopened to allow you to decide if you wanted to fix it or close it. I am switching to different CI infrastructure more under my control.

**Comment by eljobe** [comment]
I think I have figured it out. It turns out I also ran into the exact same issue on the other CI tool I was using.  So, both travis and drone use `git+https` to clone the repositories before running the builds. So, when the `ghPages` plugin looks at the `origin` to deterimne the `repoUri`, it is limited to using the https authentication which requires either a token or username/password.

The way I solved this was by explicitly setting the `repoUri` field in the plugin to be the ssh compatible one.  Then, I just had automate making an entry in the `$HOME/.ssh/known_hosts` file, and I was all set to use ssh. Yay!

You can consider the above advice a workaround and still try to make the error messages clearer, or you can just close this issue and hope others find it when they run into the same problem.
