### ISSUE TITLE
Need way to get Git hashes and commit logs on submodules

### ISSUE THREAD

**Issue by andviane** [ajoberstar/gradle-git#215]
It was a requirement for me to display Git hash codes and a few recent commits on submodules inside the project. I was not able to do so with the help of the current API. I finally managed to resolve the problem by using the wrapped instance of JGit that is thank goodness present in the repository class (grgit.repository.jgit).

Fetching the needed information requires to open the second JGit information using SubmoduleWalker. While the work around worked, it would be probably beneficial to have the submodule support built-in.

**Comment by ajoberstar** [comment]
Thanks for posting the suggestion. This would need to be implemented in [grgit](https://github.com/ajoberstar/grgit), would you mind creating the issue over there? When you do, could you add some more specifics about exactly what functionality you would need? If you have suggestions about where those would fit in the existing API, that would be great.  I don't have much experience with submodules, so I'd like to make sure I have a clear picture of what you would need.
