### ISSUE TITLE
Question - Run task based on stage

### ISSUE THREAD

**Issue by bearrito** [ajoberstar/gradle-git#216]
Version: 1.5.1

I'm running the opinionated configuration

My questions is how might I access the provided (or inferred) stage to conditionally run a task.

I'm interested in automatically publishing only if the stage is 'rc' or 'final'

**Comment by ajoberstar** [comment]
Sorry for missing this issue, hopefully I can still be of some help. One option is using the `onlyIf` on the task:

```groovy
myPublishTask {
  onlyIf { ['rc', 'final'].contains(project.findProperty('release.scope')) }
}
```
