### ISSUE TITLE
submodule seems to cause fail

### ISSUE THREAD

**Issue by pivotal-stuart-pollock** [ajoberstar/gradle-git#217]
Using a submodule:

In the submodule directory, a command-line "git" will correctly parse the _file_ .git to determine git version from HEAD.

However, using this tool seems to fail to interpret the .git of the submodule

So steps for repo:
- make one git repo a submodule of another git repo, below called "myparentproj" as parent and "mysubmoduleproj" as the submodule, such that 

```
myparentproj
    src
         mysubmoduleproj
```

is a directory structure.
- cd into the location of that submodule, e.g. cd src/mysubmoduleproj
- use the command line tool for git functions (those commands work)
- use a gradle build.gradle script in the submodule dir to get the version from HEAD, e.g. some usage like

```
jar {
    def grgit = org.ajoberstar.grgit.Grgit.open(project.projectDir)

    baseName = 'mymainproj'
    version = '0.2.0'
    classifier = grgit.head().getAbbreviatedId()
}
```

yields an error like

```
* What went wrong:
A problem occurred evaluating root project 'mysubmoduleproj'.
> repository not found: /Users/me/workspace/myparentproj/src/mysubmoduleproj
```

**Comment by ajoberstar** [comment]
Not sure if you want to open it from within the project dir in that case. You probably need to use the `currentDir` option to [Grgit.open](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/OpenOp.html). That will look up to the root one. But then you may have to deal with submodule stuff a little more. Explicit support in Grgit is pretty minimal, and there have already been a few issues reported that are actually JGit limitations. Hard for me to say whether what you're looking for will work at this point or not.
