### ISSUE TITLE
how to commit a single file to git repo

### ISSUE THREAD

**Issue by mivola** [ajoberstar/gradle-git#218]
I'm successfully using this plugin to create and push tags. But I'd also like to commit files with it. I can see here that with previous versions this was possible: https://goo.gl/HVqeVN I even manged to create a (empty) commit using this:
task commit(type: GitCommit) {
	message = "Increase buildVersion to ${project.version.toString()}"
}
I just didnt manage to add a changed file (or all changes) to this commit. Any Ideas?

Thanks a lot!
Regards,
Michael

**Comment by ajoberstar** [comment]
That particular link is to a quite old version. The [wiki](https://github.com/ajoberstar/gradle-git/wiki/Grgit%20Usage) has a more updated example of the general pattern. There's also a link there to Grgit's API which documents all of the available commands you can do.

**Comment by mivola** [comment]
Thanks for that. I did it like this:

import org.ajoberstar.grgit.*;

task commitVersionFile() << {
	def grgit = Grgit.open(dir: '.')
	grgit.add(patterns: [versionFile])
	grgit.commit(message: "updated versionFile")
	println 'Committed successfully: ' + versionFile
}

task createTag() << {
	def grgit = Grgit.open(dir: '.')
	grgit.tag.add {
		name = "RELEASE-${project.version.toString()}"
		message = "Application release ${project.version.toString()}"
	}
}
