### ISSUE TITLE
Set version as 5.0.0 for a initial release 

### ISSUE THREAD

**Issue by saraswat2385** [ajoberstar/gradle-git#219]
Hi  @ajoberstar 

I have fresh repo and want to release version v5.0.0 directly from that repo is there any option to do so using release-opinion' ?

Thanks

**Comment by ajoberstar** [comment]
For an initial seed, there's not anything you can directly do through the plugin. But you can just manually add the tag from the Git CLI. Running the build again, will keep the `5.0.0` version as long as you don't change anything in the repo after the tag.
