### ISSUE TITLE
Repository search up current project folder

### ISSUE THREAD

**Issue by ghost** [ajoberstar/gradle-git#22]
In GitBase, it might be better to enable searching the repository folder up from and inclusive the current project folder.

**Comment by lennyk** [comment]
We're sharing a repo between a backend java app and a separate frontend app. In this use case, our git repo is also in the parent directory. I see this issue is old, is there a solution for this now?

**Comment by ajoberstar** [comment]
This was fixed in Grgit 1.3.0. Grgit.open() with no args looks up from the process working directory. You can use Grgit.open(currentDir: otherDir) if you want to override where it starts walking up from.

**Comment by lennyk** [comment]
I was hoping to do this from gradle-git.  My current tack looks like this:

```groovy
task gitMetadata(type: org.ajoberstar.gradle.git.tasks.GitBranchList) << {
    repoPath = '..'
}
```

but I continue to get this error:

```bash
$ pwd
/xxxx/my-repository-folder/my-project-folder

$ gradle assemble

...

* What went wrong:
Execution failed for task ':gitMetadata'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found:
/xxxx/my-repository-folder/my-project-folder
```

what am I missing?

**Comment by lennyk** [comment]
We realized we were using an older version of Grgit. After upgrading to 1.4.0, we're not having any problems figuring this out. Thanks for your time!
