### ISSUE TITLE
custom versioning strategy

### ISSUE THREAD

**Issue by philbert** [ajoberstar/gradle-git#222]
I've been messing around with the gradle release plugin for a while now and I'm trying to customise how to determine the version and tag.

I quite like the opinionated configuration but I wanted to make a few tweaks but there aren't enough examples around that make it clear what to do.

What I've been trying to implement is something like the following:
1. set the default versioning to increment on minor value instead of patch value.
2. if there are uncommitted changes then do not apply a tag (works by default) and do not allow publishing to artifactory (works in a hacky way)

I've not yet managed to find the option to do 1, and option 2 relies on some clumsy code like this:
```
artifactory {
    if (grgit.status().clean) {
        // publish to artifactory
    } else {
        logger.error("There appear to be uncommitted changed in the workspace! Aborting")
    } 
}
```
I will accept if 2 is outside the scope of what the gradle release plugin can help me with.

Any tips for me?

**Comment by ajoberstar** [comment]
For 1, there's not a simple property to set, but it is configurable. Take a look at how [DEFAULT](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy#L283) is configured, particularly the `normalStrategy`, which you'd want to modify to end with `Normal.useScope(ChangeScope.MINOR)` instead of `PATCH`. 

For 2, it's slightly outside the scope, but I think you can do this with the `onlyIf` method on all Gradle tasks.

```groovy
artifactory { // presuming this is the task name
  // skip the task if there are any uncommitted changes
  onlyIf { grgit.status().clean }
}
```

**Comment by philbert** [comment]
Thanks @ajoberstar. I got the second part working fairly simply with 
```artifactoryPublish.onlyIf { grgit.status().clean }```

But I'm still fumbling around to solve the versioning issue. Basically I want to add my own custom versioning strategy, right? Do you have an example about how to do that? The only one I found is [this](https://github.com/tschulte/gradle-semantic-release-plugin) which looks pretty interesting but I want to start with something more simple first.

**Comment by ajoberstar** [comment]
Netflix's Nebula plugins are another example of this. See:
- [NetflixOssStrategies](https://github.com/nebula-plugins/nebula-release-plugin/blob/master/src/main/groovy/nebula/plugin/release/NetflixOssStrategies.groovy)
- [ReleasePlugin](https://github.com/nebula-plugins/nebula-release-plugin/blob/master/src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy)
