### ISSUE TITLE
Offer Gradle sample on how to publish

### ISSUE THREAD

**Issue by jnorthr** [ajoberstar/gradle-git#224]
For a user to quick-start use this org.ajoberstar.grgit plug-in, is it possible to publish a 'Hello-World' sample build.gradle script to show a project push to it's Github repo ? Maybe also a sample for maven ?

thanx for all your hard work - much appreciated !  ;-)

**Comment by ajoberstar** [comment]
I added a small task to the [Grgit Usage](https://github.com/ajoberstar/gradle-git/wiki/Grgit-Usage) wiki page that shows a basic push. As mentioned after the examples, the Grgit API doc includes details on all available operations.

When you say "a sample for Maven", do you mean Maven builds or Maven repositories? I think both are out of scope of this plugin, but if you have more clarification, please let me know.
