### ISSUE TITLE
no such property exception in gh-pages plugin

### ISSUE THREAD

**Issue by tschulte** [ajoberstar/gradle-git#226]
When the origin of build/ghpages has changed (e.g. after changing the config), an exception `no such property: logger for class: org.ajoberstar.gradle.git.ghpages.GithubPagesPlugin` is thrown.

In GithubPagesPlugin:122 it should be `project.logger` instead of just logger.

**Comment by tschulte** [comment]
Workaround: manually deleting build/ghpages

**Comment by ajoberstar** [comment]
Fixed in master. Thanks for catching that!
