### ISSUE TITLE
Question - prefixed tags to allow different version

### ISSUE THREAD

**Issue by guenhter** [ajoberstar/gradle-git#227]
Hi,

I have a question if you are interested in the following feature (if you are, I would create this as PR, else I have to search for another plugin or just fork and stay on that fork):

The following is required in my company: One single repo where, but when we release the product, we not only want to tag the build with eg. `1.0.0` but also prefix it e.g. `productA-1.0.0`. This version for this prefix is increased as used:
`productA-1.1.0`
`productA-2.0.0`.

But different prefixes have their own versioning. 
`productB-1.0.0`
`productB-1.1.0`
`productB-1.2.0`.
...

So the main feature would be, to always consider a prefix when existing tags are checked. By default, the prefix is empty, and so the versioning is not changed. If a prefix is set, only those tags are considered. 
With this, it would be possible, to maintain different products with seperate tags in one repo, or even tag the same product with different tag-meandings. (e.g. 1.0.0, 2.0.0, 3.0.0, LTS-1.0.0).

**Comment by guenhter** [comment]
After a quick look at the code, I think all of this can e managed within the `TagStrategy`.
To avoid breaking anything, it might be a good idea, to extract an interface from the current `TagStrategy` and enable the current one as it is by default. 
A second implementation of that `TagStrategy`-Interface with this functionality could exist. It can be enabled if needed

```
release {
    tagStrategy = TagStrategies.PREFIX
    
    tagStrategy {
        prefix = "productA"
    }
}
```

**Comment by guenhter** [comment]
In fact, the current `TagStrategy` already contains a light variant of prefixing: `setPrefixNameWithV`

**Comment by ajoberstar** [comment]
I think you can already do this by customizing `toTagString` and `parseString` in the [TagStrategy](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/base/TagStrategy.groovy).

**Comment by guenhter** [comment]
Thanks

works perfectly fine

```
plugins {
    id "org.ajoberstar.release-base" version "1.6.0"
}

ext.prefix = "prefix."

import org.ajoberstar.gradle.git.release.opinion.Strategies
release {
    grgit = org.ajoberstar.grgit.Grgit.open(dir: project.rootDir)
    versionStrategy Strategies.FINAL
    defaultVersionStrategy Strategies.SNAPSHOT

    tagStrategy {
        toTagString = { versionString -> "${prefix}${versionString}" }
        parseTag = { org.ajoberstar.grgit.Tag tag ->
            if ( !tag.name.startsWith("${prefix}")) return null

            try {
                com.github.zafarkhaja.semver.Version.valueOf(tag.name["${prefix}".size()..-1])
            } catch (com.github.zafarkhaja.semver.ParseException e) {
                null
            }
        }
    }
}
```

IMO it would fine though if the TagStrategy is more generic and different variants exists. Maybe consider this for version 2.x. I'm also glad if I could help you refactor on this area.

**Comment by ajoberstar** [comment]
While I haven't worked on it in a while [semver-vcs](https://github.com/ajoberstar/semver-vcs) is the effective 2.0 for the release plugins.
