### ISSUE TITLE
 One of setGitDir or setWorkTree must be called

### ISSUE THREAD

**Issue by criztovyl** [ajoberstar/gradle-git#228]
```
An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version: '1.6.0']
> Failed to apply plugin [id 'org.ajoberstar.grgit']
   > One of setGitDir or setWorkTree must be called.
```

I re-rerun with `--stacktrack`, which leads to [org.ajoberstar.gradle.git.base.GrgitPlugin#apply](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/base/GrgitPlugin.groovy#L34)

    Caused by: java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.

I think jgit changed the exception thrown if the no Git repo is found.

~~Will attach full stacktrace soon.~~ Done.

**Comment by criztovyl** [comment]
[stacktrace.txt](https://github.com/ajoberstar/gradle-git/files/602065/stacktrace.txt)

**Comment by ajoberstar** [comment]
Yeah, that seems pretty likely. I'll mark this a bug and double-check that. Thanks for reporting.

**Comment by criztovyl** [comment]
I'll make a PR :)

**Comment by criztovyl** [comment]
[org.eclipse.jgit.storage.file.FileRepositoryBuilder#build](http://download.eclipse.org/jgit/site/4.5.0.201609210915-r/apidocs/org/eclipse/jgit/storage/file/FileRepositoryBuilder.html#build--)

**Comment by criztovyl** [comment]
The Exception seems to come from here: [org.ajoberstar.grgit.operation.OpenOp#call](https://github.com/ajoberstar/grgit/blob/master/src/main/groovy/org/ajoberstar/grgit/operation/OpenOp.groovy#L86)

**Comment by criztovyl** [comment]
Maybe there should be a final `getGitDir()` check after `builder.findGitDir()`.

**Comment by criztovyl** [comment]
So, this seems to be a *grgit* issue, not *gradle-git*, I'll move there :)

**Comment by ajoberstar** [comment]
Reopening since I need to depend on the fixed grgit version.

**Comment by jessiepoquerusse** [comment]
I'm still encountering the same issue as criztovyl on 11/20/16. I'm confused about what the consensus for resolution was..?

**Comment by criztovyl** [comment]
Sorry for the mess of issues and pr's.
The resolution done by ajoberstar/grgit#129 should be in mainline now.
What's your gradle-git version? :)

**Comment by jessiepoquerusse** [comment]
This version: https://github.com/ajoberstar/gradle-git 
With Gradle 2.10 :)

**Comment by ajoberstar** [comment]
This fix was added in v1.7.2 of grgit (which is a dependency of gradle-git), so it should be fixed in gradle-git 1.7.0 or higher.

If you're using classic syntax plugins:

```groovy
buildscript {
  // ... repositories ...
  dependencies {
    classpath 'org.ajoberstar:gradle-git:1.7.0' // or higher
  }
}
```

If you're using plugin block:

```groovy
plugins {
  id 'org.ajoberstar.grgit' version '1.7.0' // or higher
}
```

**Comment by ajoberstar** [comment]
The grgit 2.x and beyond plugin is hosted in [grgit](https://github.com/ajoberstar/grgit). Could you open an issue over there and include the full stacktrace you're seeing?

**Comment by langsmith** [comment]
Ok, will do @ajoberstar . Thanks
