### ISSUE TITLE
concurrent development and impact for merge 

### ISSUE THREAD

**Issue by kknd22** [ajoberstar/gradle-git#231]
We have been using this great plugin very successfully in our CI/CD pipeline. I have a question of the  behavior of the version for the build after maintenance branch merged to a development branch.

Scenario:
   Maintenance  branch: 1.0.x
   Development branch: 2.0.x   (branch off from 1.0.2)

Timeline:

branch **1.0** `  1.0.0 -> 1.0.1 -> 1.0.2 -> -------------->1.0.3---|`
`____________________________________________________________V (merge)`
branch **2.0** `  _____________________________| -> 2.0.0 -> 2.0.1   ----> ???`

We were expecting the next version should be 2.0.2 but it is 1.0.4 instead.
`git describe` on branch 2.0 is 1.0.3, instead of the excepted 2.0.1
So is it a correct behavior? If not, is there a workaround, if yes, what is the suggested  way to handle this kind of concurrent development?

Thanks
-Chris L.

**Comment by ajoberstar** [comment]
This is an expected, though not really correct, behavior. The main logic is based on which tag is "closest" (by number of commits) to the current branch head. If you merge in a branch that just tagged a release that will get picked up.

This is related to #115, there more specific to gitflow style approaches, but I think it's the same underlying problem. As I indicated there, it's kinda thorny to figure out so my plan is to address it in the [semver-vcs](https://github.com/ajoberstar/semver-vcs) plugin that would succeed the release plugins here. Granted, that's been sitting out there for a while, so don't know when that would happen.

If you have thoughts on how to address this or more use cases that should be addressed please add them on the other issue. I'll mark this one a duplicate.
