### ISSUE TITLE
Update Grgit dependency

### ISSUE THREAD

**Issue by phatblat** [ajoberstar/gradle-git#242]
[Grgit 1.8.0](https://github.com/ajoberstar/grgit/releases/tag/1.8.0) has been released, but the dependency in this project is fixed to [1.7.0](https://github.com/ajoberstar/gradle-git/blob/master/build.gradle#L45).

This can be worked around with a resolutionStrategy like the following, but it would be ideal if the dependency version could be updated.

```gradle
buildscript {
    dependencies {
        classpath 'org.ajoberstar:gradle-git:1.6.0'
    }
    configurations.all {
        resolutionStrategy.dependencySubstitution {
            substitute module('org.ajoberstar:grgit') with module('org.ajoberstar:grgit:1.8.0')
        }
    }
}
```

**Comment by ajoberstar** [comment]
This will be out tonight as 1.7.0
