### ISSUE TITLE
versioning is confusing

### ISSUE THREAD

**Issue by jjkoehorst** [ajoberstar/gradle-git#247]
I am very new to gradle so it could be me but I wanted to tryout the plugin and added it to the plugin section:

    id 'org.ajoberstar.grgit' version '1.7.0'

Which could not be found but 1.6.0 is available which then downloads 1.7.0?

    gradle build 
    Download https://plugins.gradle.org/m2/org/ajoberstar/gradle-git/1.6.0/gradle-git-1.6.0.pom
    Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/1.7.0/grgit-1.7.0.pom

**Comment by ajoberstar** [comment]
1.7.0 isn't in the plugin portal yet (technical difficulties), so the plugins block can't see it. If you used the old buildscript approach you can get it from Jcenter.

That 1.7.0 you see downloaded is a dependency of gradle-git, called grgit.

**Comment by jjkoehorst** [comment]
Thanks, is there a way that a warning is given when a newer version becomes available?

**Comment by ajoberstar** [comment]
Bintray lets you watch packages, which I think notifies when new releases come out: [gradle-git package](https://bintray.com/ajoberstar/maven/gradle-git).
