### ISSUE TITLE
release opinion deploy on nexus repository

### ISSUE THREAD

**Issue by enrico-dimarco** [ajoberstar/gradle-git#253]
Hi,
I'm experiencing an issue with release-opinion plugin; every build is uploaded to release plugin in nexus repository, i would expect dev versions to be uploaded on snapshot repository and rc and milestones and finals to release repository;
is there a sample configuration i can use or something I'm missing ?
my actual config is:

       group = 'social.picnik.backend'
        
        plugins {
            id 'org.ajoberstar.grgit' version '1.7.0'
            id 'org.ajoberstar.git-publish' version '0.2.0'
        
        // if you want to use the opinionated config
            id 'org.ajoberstar.release-opinion' version '1.7.0'
        
        // if you want to configure it to your preferences
        //    id 'org.ajoberstar.release-base' version '1.7.0'
        }
        
        
        apply plugin: 'java'
        apply plugin: 'maven'
        
        
        
        //version = '3.31.3-SNAPSHOT'
        
        description = " --backend-services-- "
        
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
        tasks.withType(JavaCompile) {
            options.encoding = 'UTF-8'
        }
        
        tasks.release.dependsOn 'build', 'uploadArchives'
        
        
        uploadArchives {
            repositories {
                mavenDeployer {
                    repository(url: "${nexusUrl}/content/repositories/releases") {
                        authentication(userName: nexusUsername, password: nexusPassword)
                    }
                    snapshotRepository(url: "${nexusUrl}/content/repositories/snapshots") {
                        authentication(userName: nexusUsername, password: nexusPassword)
                    }
                }
            }
        }
        
        wrapper {
            gradleVersion = '3.4'
        }

when i run the command 
>gradle release 

the plugin infer the version correctly as 3.31.3-dev.22.uncommitted+c6e4922 
but then i find the jar on nexus in release repository (even if nexus is giving 400 response code)

do you have any suggestion ?

**Comment by ajoberstar** [comment]
I think snapshot repos are only for literal `-SNAPSHOT` versions.

**Comment by ajoberstar** [comment]
Feel free to reopen if this did not answer your question.

**Comment by Miamoto-Musashi** [comment]
thanks it does not solves my problem but it does answer, I could solve the problem using nebula-release plugin
thanks for your time
