### ISSUE TITLE
release plugin is applied to CompositeBuilds

### ISSUE THREAD

**Issue by rodney757** [ajoberstar/gradle-git#255]
When using the opinion-release plugin with composite builds, there is no way apply the version resolution to only the rootProject.

Ex.

I use the release plugin in a "gradle-plugin" project. I also use the release plugin in project "A".
project "A" is composite build, including project "gradle-plugin". 

If "gradle-plugin" is "dirty", and I run "gradle release -Prelease.stage=final" from project "A", the build fails saying that it can't resolve the version for "gradle-plugin". The same thing happens if I call the release task on the rootProject ":release".

It would be nice if we could somehow specify which project to apply the release plugin to, or to at least, ignore the version resolution if this is a composite build

**Comment by ajoberstar** [comment]
I haven't spent much time with composite builds yet, so I'm not sure if there's a way to detect this scenario. Not sure when I'll get to looking into this in more detail, but let me know if you determine anything that seems like a solution.

**Comment by ajoberstar** [comment]
As is now noted in the README, I won't be enhancing gradle-git any further (but will still do some bug fixes). For this particular issue, I'd want to address it in [reckon](https://github.com/ajoberstar/reckon) which is the long-term replacement for the release plugins. If there's a clean way to address this here without breaking any current behavior I'm open to that too.
