### ISSUE TITLE
Dependency to grgit 1.9.3 missing in maven central

### ISSUE THREAD

**Issue by vojbarzz** [ajoberstar/gradle-git#259]
Hello,

I have found that dependency to 'org.ajoberstar:grgit:1.9.3' is missing in maven central. Check http://search.maven.org/#artifactdetails%7Corg.ajoberstar%7Cgradle-git%7C1.7.2%7Cjar and http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.ajoberstar%22%20AND%20a%3A%22grgit%22.

Thank You

**Comment by ajoberstar** [comment]
Long term, I'll probably only be publishing to JCenter, since it requires less work to get things published. At the moment gradle-git is still being published there, but I don't expect to continue that.
