### ISSUE TITLE
Republishing to Nexus in case of no new commits

### ISSUE THREAD

**Issue by Ponai** [ajoberstar/gradle-git#269]
When executing the release task on a branch with no new commits after the already tagged and released version, the plugin tries to re-release the version.

This has at least one unwanted side-effect: the plugin tries to republish already published release versions to the used repository manager(s).

Expected behaviour: republishing already released versions is not allowed and the plugin should warn the user of this fact and the release procedure should be aborted (no publish to a repository manager)

**Comment by ajoberstar** [comment]
The gradle-git plugin doesn't provide anything for publishing, so I'm not sure there's anything that could be done here. There's a prepare task and a release task that cover the Git tag/push. But besides that, the plugin relies on the user adding dependencies on other tasks they want included in the release.

Let me know if I'm misunderstanding what you're looking for.

**Comment by Ponai** [comment]
Maybe then my setup is wrong.
Basically what I want to prevent is the republishing of already released
versions.
Somehow as I see it, the release task could remove all tasks that depend on
it from the taskgraph to prevent them from being executed in case there is
nothing new to be released, but that may not be a recommended Gradle
solution.
Which solution could you recommend to avoid the republishing scenario?


Op 28 sep. 2017 03:21 schreef "Andrew Oberstar" <notifications@github.com>:

The gradle-git plugin doesn't provide anything for publishing, so I'm not
sure there's anything that could be done here. There's a prepare task and a
release task that cover the Git tag/push. But besides that, the plugin
relies on the user adding dependencies on other tasks they want included in
the release.

Let me know if I'm misunderstanding what you're looking for.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ajoberstar/gradle-git/issues/269#issuecomment-332699944>,
or mute the thread

**Comment by Ponai** [comment]
Maybe an up-to-date when head is tagged with a version compatible with the
release context?

Op 28 sep. 2017 03:21 schreef "Andrew Oberstar" <notifications@github.com>:

**Comment by ajoberstar** [comment]
You could add an `onlyIf` check on the tasks you don't want rerun that would check if the project version already has a tag. I don't think this is a good general solution, but may work for what you're describing.

As for any changes in gradle-git itself, given the status of the project (see the readme), I won't be doing anything more than bug fixes.
