### ISSUE TITLE
Un-private ReleasePluginExtension.DelayedVersion

### ISSUE THREAD

**Issue by grv87** [ajoberstar/gradle-git#272]
I would like to get `version.inferredVersion` from Java. Unfortunately, it is not possible since ReleasePluginExtension.DelayedVersion class is private. Could you change that?

**Comment by ajoberstar** [comment]
I'm generally trying to minimize changes to gradle-git (you can see why in the README).

If you just need the version itself, you can use `project.version.toString()` to get that.

If you're looking for some of the fields on the `ReleaseVersion` class, can you provide more information about your use case?

**Comment by grv87** [comment]
I'm passing `project.version.inferredVersion.previousVersion` and `project.version.inferredVersion` to [`SemanticReleaseChangeLogService`](https://github.com/tschulte/gradle-semantic-release-plugin/blob/master/src/main/groovy/de/gliderpilot/gradle/semanticrelease/SemanticReleaseChangeLogService.groovy) to get generated changelog:
```
SemanticReleaseChangeLogService changeLogService = project.getExtensions().getByType(SemanticReleasePluginExtension.class).getChangeLog();
changeLogService.changeLog(changeLogService.commits(Version.valueOf(((ReleasePluginExtension.DelayedVersion)project.version).inferredVersion.previousVersion)), version.inferredVersion);
```

**Comment by grv87** [comment]
OK, I see that this project is deprecated.
I'll use dynamic Groovy instead and wait for semantic-release plugin rewritten for reckon.
