### ISSUE TITLE
Plugin with id 'github-pages' not found

### ISSUE THREAD

**Issue by volgar1x** [ajoberstar/gradle-git#32]
Hi,
I really enjoy your Git tasks but I do not know how to install the 'github-pages' plugin. Here is my `deploy.gradle` : 

``` groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.ajoberstar:gradle-git:0.6.3'
    }
}

import org.ajoberstar.gradle.git.tasks.*

apply plugin: 'github-pages'
```

I probably forgot to add some lines

**Comment by freshcodemonger** [comment]
apply plugin: org.ajoberstar.grgit.gradle.GrgitPlugin
