### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by nhaarman** [ajoberstar/gradle-git#64]
I'm using the following script:

    import org.ajoberstar.grgit.*;

    buildscript {
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath 'org.ajoberstar:gradle-git:0.9.+'
        }
    }

    ext.repo = Grgit.open(project.file('../'))
    ext.tagList = ext.repo.tag.list()
    ext.tag = tagList.get(tagList.size() - 1).getName()

    if (isRelease == 'false') {
        int lastNumber = Integer.parseInt(tag.substring(tag.size() - 1))
        ext.tag = tag.substring(0, tag.size() - 1) + (lastNumber + 1);
    }

When this script is active, I get a lot of `java.lang.OutOfMemoryError: PermGen space` errors. Killing the java process solves the problem for a short while. Possibly a memory leak somewhere? I have confirmed that this issue does not occur when I disable that script.

**Comment by ajoberstar** [comment]
I'm closing this for now, but if anyone has more information feel free to reopen.
