### ISSUE TITLE
 Feature request: configurable tag prefix

### ISSUE THREAD

**Issue by asoee** [ajoberstar/gradle-git#83]
It would be nice if the tag prefix could be configured to something other than 'v'
Filtering for that prefix when resolving earlier versions void be very useful too.
That would make it possible to use the release plugin on a project where there is multiple different "products" in the same git repository, with each their own release/version cycle.

**Comment by hierynomus** [comment]
Andrew, we have a similar constraint. I want to use your release plugin for releasing our 50+ repositories. All of them use the following tagging convention `${rootProject.name}-x.y.z`. I would like to improve this functionality without introducing too many breaking changes.

I have a number of different approaches in mind:
1. Add 2 closures to the `TagStrategy` (a `parseTag(Tag)` and a `toTagString(ReleaseVersion)`. 
2. Introduce a new class `TagHandler` which contains the `parseTag` and `toTagString` methods.

Whatever choice, it needs to be injected into the `NearestVersionLocator`, which is constructed from the `SemVerStrategy` and `RebuildVersionStrategy`, as well as the `TagStrategy` itself, which writes the tag. 

The nice thing about creating a new `TagHandler` class is that its responsibility is very obvious, and we can easily supply a single default implementation which works how it is now, without breaking any backwards compatibility, while allowing to construct objects configured with a different `TagHandler`.

What do you think?

BTW: Great to see you're using my license plugin! :+1:

**Comment by ajoberstar** [comment]
Jeroen, I hope to address this type of need in [semver-vcs](https://github.com/ajoberstar/semver-vcs), though I don't know when it will reach parity with gradle-git's functionality. I would be OK with a change here that is backwards compatible. Would you be able to write up more specifically what API changes would be involved in your preferred solution?

**Comment by hierynomus** [comment]
Andrew, I'll try to flesh out a PR today/tomorrow, so that we can discuss
further!

2015-12-15 15:39 GMT+01:00 Andrew Oberstar <notifications@github.com>:

**Comment by hierynomus** [comment]
Looking at [ajoberstar/semver-vcs](https://github.com/ajoberstar/semver-vcs), two of the main issues that I'd be interested in before being able to use it would be ajoberstar/semver-vcs#11 and ajoberstar/semver-vcs#19.

Esp. for ajoberstar/semver-vcs#11, we have multiple maintenance branches for our products, which should dictate the `major` and `minor` component of the version. Only the `patch` should ever be incremented on those branches.

**Comment by ajoberstar** [comment]
Yeah, those issues are two of the big improvements over the existing plugin.

**Comment by hierynomus** [comment]
Thanks for merging! Any idea of when you'll be making a (new) release?

**Comment by ajoberstar** [comment]
My goal is to fix the two other stories marked for [1.4.0](https://github.com/ajoberstar/gradle-git/milestones/1.4.0) before releasing. However, I'll plan to get a release out this weekend, even if I don't get those two wrapped up.

**Comment by diegobmd** [comment]
Any example to use tag strategy like ${rootProject.name}-x.y.z, i have tag already generate with maven and i should use same pattern

Tanks

**Comment by hierynomus** [comment]
Hi @diegobmd,

You can set ip up like this:

```
release {
  grgit = org.ajoberstar.grgit.Grgit.open(project.projectDir)
  tagStrategy {
    toTagString = { vs -> "${project.name}-$vs" }
    parseTag = { org.ajoberstar.grgit.Tag tag ->
      if (tag.name.startsWith(project.name)) {
        print("Found tag: ${tag.name}")
        try {
          com.github.zafarkhaja.semver.Version.valueOf(tag.name[project.name.size() + 1..-1])
        } catch (Exception e) {
          null
        }
      } else {
        null
      }
    }
  }
}
```
