### ISSUE TITLE
add usage docs

### ISSUE THREAD

**Issue by jzwolak** [ajoberstar/gradle-git#86]
There used to be usage documentation explaining how to make a release with commands like "gradle release", "gradle release -Prelease.stage=final", etc..  I'm also curious how these command line options interact with the release strategies.

A specific section in the Wiki on "Usage" or "Making a Release" would be very helpful!

**Comment by ajoberstar** [comment]
I've tried to consolidate some of the other docs to more directly address general usage. If it's falling short of what you were getting at, please let me know more detail about what might be helpful.

See [Release Plugins](https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins%201.x) for the new doc.

**Comment by jzwolak** [comment]
That's along the lines of what I'm looking for, thanks!

Also, there is a typo in:

./gradlew release -Prelease.scope=final -Prelease.scope=major

The first property should probably be "release.stage", right?

**Comment by ajoberstar** [comment]
Yep. Nice catch.
