### ISSUE TITLE
Push single tag to the server

### ISSUE THREAD

**Issue by fourier** [ajoberstar/gradle-git#95]
Is where any way to push only particular named tag? From the PushOp class description it is either all or none. TagAddOp class doesn't have the push method.

**Comment by ajoberstar** [comment]
Haven't tested this, but I think you can push a specific tag by including it in the `refsOrSpecs` property of `PushOp`. You're correct that the `tags` flag is only meant for pushing *all* tags. You may need to include the fully qualified ref name (e.g. `refs/tags/my-tag`)

**Comment by ajoberstar** [comment]
Feel free to reopen if that didn't answer your question.

**Comment by fourier** [comment]
Thanks, I didn't try it yet since at the moment it is ok to push all tags for my environment. Will return to this issue later if configuration changes.
