### ISSUE TITLE
Semantic Versioning documentation clarification question

### ISSUE THREAD

**Issue by martinda** [ajoberstar/gradle-git#98]
> The nearest version is determined from the size of the commit logs between tags that can be parsed as version numbers and the current HEAD. 

I am not sure I understand "the size of the commit logs". Three small commits logs vs. one bigger commit log?

Do you mean: 
The nearest version is determined by the distance (in commits) between the tags that can be parsed as version numbers and the current HEAD.

Or: ... is determined by the number of commits between ...?

Or does the cumulative size of the commit logs between HEAD and the nearest semantic tag matter?

**Comment by ajoberstar** [comment]
The number of commits between the HEAD and the tag. I'll update the docs to be more clear, that sentence is pretty bad.
