### ISSUE TITLE
java 6

### ISSUE THREAD

**Issue by dmodoomsirius** [ajoberstar/gradle-git#99]
just wanted to let you know the gradle-git gradle plugin does not work on java 6.

**Comment by ajoberstar** [comment]
That's intentional. I compile for Java 7.

**Comment by ajoberstar** [comment]
The less blunt answer is that I use a few Java 7 APIs as part of the underlying `grgit` library. They may not be entirely essential, but I want to have the freedom to use Java 7 APIs more widely without needing to make a major version change.
